### PR TITLE
fix(vitest): use `fast-glob` instead of `tinyglobby` in Vitest

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

The team decided to revert to `fast-glob` until the symlink issue is resolved.

We are keeping the `tinyglobby` package in other dependencies.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by hi-ogawa — APPROVED** [review]
Thanks!

**Comment by SuperchupuDev** [comment]
@sheremet-va the symlinks issue should be solved now in 0.2.10

**Comment by benmccann** [comment]
It looks like @hi-ogawa has a PR out for some work using `tinyglobby`: https://github.com/vitest-dev/vitest/pull/6600. Hopefully if it is switched from the pkg.pr.new version to the released version everything should work

**Comment by hi-ogawa** [comment]
@SuperchupuDev Hi, thanks for the fix! We went with reverting tinyglobby for now, but we plan to revisit in next major or minor releases. We had a few back and forth with the transition, so we'll just hold off for a moment. I appreciate what you do with tinyglobby :pray:

**Comment by benmccann** [comment]
Is there anything we could help with to get it working in one of the upcoming minor releases?

**Comment by benmccann** [comment]
Vite 6 is out now, which migrated from fast-glob to tinyglobby ([changelog](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#breaking-changes)). I wonder if that might make it a good time to try again here?

**Comment by hi-ogawa** [comment]
Yeah, we can bring back tinyglobby for Vitest v3. Please feel free to send a PR :+1:

**Pull request merged**
