### PR TITLE
fix: make report less verbose when running in CI

### LINKED ISSUE #905: Logs are too verbose for CI
### Describe the bug

When building on the CI each it/test will be outputted on the CI, but generally we only care about the failed tests, the passed can be grouped by file (like is it when we run locally)

Currently on a code base I'm working on, we are getting warning on Circle CI 
```bash
Your output is too large to display in the browser.

Only the last 400000 characters are displayed.
```

When running vitest
```bash
candidate "wait 1023 HOUR for TOP RIGHT DROPDOWN "Compound Name"" as "'Compound Name'" for "HOUR
 √ tests/parse-wait.test.ts > parse a natural language test step into an object > using target `TOP RIGHT DROPDOWN "Compound Name" > should parse candidate "wait 1023 HOURS for TOP RIGHT DROPDOWN "Compound Name"" as "'Compound Name'" for "HOURS
 √ tests/parse-wait.test.ts > parse a natural language test step into an object > using target `TOP RIGHT DROPDOWN "Compound Name" > should parse candidate "wait 1023 for TOP RIGHT DROPDOWN "Compound Name"" as "'Compound Name'"
 √ tests/parse-wait.test.ts > parse a natural language test step into an object > using target `TOP LEFT DROPDOWN "Compound Name" > should parse candidate "wait 1023 ms for TOP LEFT DROPDOWN "Compound Name"" as "'Compound Name'" for "ms
 √ tests/parse-wait.test.ts > parse a natural language test step into an object > using target `TOP LEFT DROPDOWN "Compound Name" > should parse candidate "wait 1023 s for TOP LEFT DROPDOWN "Compound Name"" as "'Compound Name'" for "s
/// many more lines
```

When running Jest
```bash
yarn workspace v1.22.5
yarn run v1.22.5
$ jest -w 3 --logHeapUsage --ci
 PASS  tests/parse-execute.test.ts (72 MB heap size)
 PASS  tests/completer/completer-execute.test.ts (74 MB heap size)
 PASS  tests/parse.test.ts (90 MB heap size)
 PASS  tests/completer/completer-cookie.test.ts (114 MB heap size)
// etc
```

### Reproduction

https://github.com/unocss/unocss/runs/5404907223?check_suite_focus=true#step:8:14 

Or any other project with CI running vitesse.

### System Info

```shell
Non-relevant, happens on Github CI, Circle CI, etc.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #905

### CODE REVIEW

**Comment by sheremet-va** [comment]
This change basically makes `isTTY` absolete

@antfu what are usecases for showing every passing test one by one? Maybe we should make it a config option?

**Comment by antfu** [comment]
I think for the default reporter, it should behave the at least similiar for tty/non-tty. If we want to make it less versbose we could change the reporter in CI.

**Comment by sheremet-va** [comment]
> I think for the default reporter, it should behave the at least similiar for tty/non-tty (not neccesry CI, ppl might use that more to dev without tty). If we want to make it less versbose we could change the reporter in CI.

I don't understand what you are suggesting 👀

**Comment by antfu** [comment]
Emm, I don't understand you either :P What's the difference across this change?

**Comment by sheremet-va** [comment]
> Emm, I don't understand you either :P What's the difference across this change?

This change makes terminal behave the same in dev and CI enviroments. Currently in CI it prints every test that passed/errored instead of the file paths like in dev. So I am not sure what the usecase here - why would I want to see every defined `test` in CI?

**Comment by sheremet-va** [comment]
> > Emm, I don't understand you either :P What's the difference across this change?
> 
> This change makes terminal behave the same in dev and CI enviroments. Currently in CI it prints every test that passed/errored instead of the file paths like in dev. So I am not sure what the usecase here - why would I want to see every defined `test` in CI?

So, in dev its:
```
PASS tests/test.test.ts
```
But in CI its
```
PASS test/test.test.ts > describe > another describe > test 1
PASS test/test.test.ts > describe > another describe > test 2
PASS test/test.test.ts > describe > another describe > test 3
PASS test/test.test.ts > describe > another describe > test 4
PASS test/test.test.ts > describe > another describe > test 5
PASS test/test.test.ts > describe > another describe > test 6
PASS test/test.test.ts > describe > another describe > test 7
PASS test/test.test.ts > describe > another describe > test 8
```

**Comment by sheremet-va** [comment]
> > > Emm, I don't understand you either :P What's the difference across this change?
> > 
> > 
> > This change makes terminal behave the same in dev and CI enviroments. Currently in CI it prints every test that passed/errored instead of the file paths like in dev. So I am not sure what the usecase here - why would I want to see every defined `test` in CI?
> 
> So, in dev its:
> 
> ```
> PASS tests/test.test.ts
> ```
> 
> But in CI its
> 
> ```
> PASS test/test.test.ts > describe > another describe > test 1
> PASS test/test.test.ts > describe > another describe > test 2
> PASS test/test.test.ts > describe > another describe > test 3
> PASS test/test.test.ts > describe > another describe > test 4
> PASS test/test.test.ts > describe > another describe > test 5
> PASS test/test.test.ts > describe > another describe > test 6
> PASS test/test.test.ts > describe > another describe > test 7
> PASS test/test.test.ts > describe > another describe > test 8
> ```

**Comment by sheremet-va** [comment]
Closed by mistake :P

----
I'm also unsure why the decision to do this is depending on `isTTY` a, which depends on `CI` and `isTTY` - shouldn't it be another variable?

**Comment by antfu** [comment]
In TTY modes, the sub tests will be displayed but eased out when all passes. In non-TTY you can 't ease out the already printed content, so it will display flatly. I make this because I think know whether a test is running is important feedback. Image you have very long running sub tests under a file, you can always see which one is running in TTY, but if we take your approach, in non-TTY you won't be able to know which sub tests are running but only the file.

**Comment by sheremet-va** [comment]
> In TTY modes, the sub tests will be displayed but erased out when all passes. In non-TTY you can 't erase out the already printed content, so it will display flatly. I make this because I think know whether a test is running is important feedback. Image you have very long running sub tests under a file, you can always see which one is running in TTY, but if we take your approach, in non-TTY you won't be able to know which sub tests are running but only the file.

I haven't expirienced this problem with Jest. It just prints the files that are running, Why we can't do that?
If I have a lot of tests, CI warns "Your output is too large to display", see #905

**Comment by sheremet-va** [comment]
> 

Also the only time I want to see this is when I debug why my tests are taking long to execute.

**Comment by antfu** [comment]
Ok, I am fine with the change. We could leave it for the `verbose` reporter. But check the CI, it seem your change does not affecting the result 👀

**Comment by sheremet-va** [comment]
> But check the CI, it seem your change does not affect the result 👀

I guess `isTTY` returns false here? 👀 Than I'm not sure what to do, make another option in config?

**Comment by antfu** [comment]
isTTY is always false in CI. Just change the code for outputing. Using different reporter is already serve the functionality as options.

**Pull request closed without merging**
