### PR TITLE
fix: compatibility with `jest`'s `toStrictEqual`

### PR DESCRIPTION
**Pull request by Shinigami92**
Make `toStrictEqual` compatible with jest's version

https://jestjs.io/docs/expect#tostrictequalvalue

### CODE REVIEW

**Comment by Shinigami92** [comment]
Solves my comment in #43

**Comment by Shinigami92** [comment]
I found this lines, but I'm sure we cannot just steal them, can we?
https://github.com/facebook/jest/blob/523fa7ee7666322dfad4833b4aa6243da1a11b1b/packages/expect/src/matchers.ts#L63-L66

**Comment by Shinigami92** [comment]
Tested this current draft with my plugin-pug and it fixes my issue with `toStrictEqual` :tada: 
But jest does have 2 more matchers after these two comparisons :thinking:

**Comment by patak-dev** [comment]
Could you add some tests for these cases? Not everything from here: https://github.com/facebook/jest/blob/c7397485f11e27d0e03f647283c2c9d9b6ce33ea/packages/expect/src/__tests__/matchers.test.js#L290, but at least some basic ones that test the different custom matches that were just added.

**Review by patak-dev — APPROVED** [review]

**Comment by Shinigami92** [comment]
> Could you add some tests for these cases? Not everything from here: [facebook/jest@`c739748`/packages/expect/src/__tests__/matchers.test.js#L290](https://github.com/facebook/jest/blob/c7397485f11e27d0e03f647283c2c9d9b6ce33ea/packages/expect/src/__tests__/matchers.test.js#L290), but at least some basic ones that test the different custom matches that were just added.

Already did :thinking: 

https://github.com/vitest-dev/vitest/pull/330/files#diff-2533cdb9583305f3b05fad10be6281af52a29e972dd0dc844c023c9d86f8a831R165

**Comment by patak-dev** [comment]
Sorry, I missed that, I was looking to your last changes and forgot to switch when checking the tests

**Pull request merged**
