### PR TITLE
feat: outputTruncateLength option

### LINKED ISSUE #962: Option to customize the maximum truncated output
### Clear and concise description of the problem

Currently Vitest uses `process.stdout.columns || 80` as the limit of diff output. It would be great to have a way to customize that size, especially when you have a really long test snapshot.

```diff
- Expected   "something …
+ Received   "something …
```

### Suggested solution

An `outputTruncateLength` option.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #962

### CODE REVIEW

**Comment by Dragomir-Ivanov** [comment]
Thanks for your feature.
Looking at the commit it looks like that this is only length of the lines. I.e. more than 80 columns.
Is there any option to modify number of lines output. I have some big JSON structures to diff.

Thanks.

**Comment by Inviz** [comment]
I want to join to this, it is quite unusable with short diff atm @Aslemammad

**Comment by Inviz** [comment]
Oh there's an option now. This can work. However I think diff reporter is the weakest part of vitest experience atm.

**Comment by Aslemammad** [comment]
@Inviz Feel free to create an issue that helps us with improving the diff reporter!

**Pull request merged**
