### PR TITLE
chore: add team member

### PR DESCRIPTION
**Pull request by dammy001**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by sheremet-va — APPROVED** [review]

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Sorry, just checked! You have a "contributors" role, not the team role, I'm sorry. We have a few people there and we are very grateful for your contribution 🙏🏻 But at the moment we only list "team" members here

**Comment by antfu** [comment]
We could have a dedicated team page like Vite to list all of them as well as the past members

**Comment by sheremet-va** [comment]
> We could have a dedicated team page like Vite to list all of them as well as the past members

I am not sure if Vite has a separate section for notable contributors who are not on the team. I definitely think we need a page with team members and team emeriti (people who were previously on the team), but "contributors" is the first step to become a team member.

**Comment by userquin** [comment]
https://vitejs.dev/team.html

**Pull request closed without merging**
