### PR TITLE
fix: repeatable `--exclude` option

### PR DESCRIPTION
**Pull request by fregante**
### Description

- Fixes https://github.com/vitest-dev/vitest/issues/5779

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by fregante** [comment]
@sheremet-va fixed

**Review by sheremet-va — DISMISSED** [review]

**Comment by sheremet-va** [comment]
Test is failing

**Comment by fregante** [comment]
> Test is failing

Either the CLI parser is bugged (`--exclude="a/*"` should not be ready as `\"a/*\"`) or I escaped the glob the wrong way (should it be `"--exclude=a/*"`? or just `--exclude=a/*`?)

Either way that's a separate issue that I just avoided by dropping the glob here.

**Review by sheremet-va — APPROVED** [review]

**Comment by fregante** [comment]
Thank you for merging! Is this expected to hit v1 releases or is everything on hold until v2?

**Comment by sheremet-va** [comment]
Everything is on hold until v2

**Pull request merged**
