### PR TITLE
docs: add migration guide from Vitest 0.34

### PR DESCRIPTION
**Pull request by sheremet-va**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by AriPerkkio — COMMENTED** [review]
Should we also add links to relevant PRs? Those might provide additional information reasoning why breaking changes were made. 

```diff
- ### Timer mocks 
+ ### Timer mocks [#3925](https://github.com/vitest-dev/vitest/pull/3925)
```

**Comment by dammy001** [comment]
> Should we also add links to relevant PRs? Those might provide additional information reasoning why breaking changes were made.
> 
> ```diff
> - ### Timer mocks 
> + ### Timer mocks [#3925](https://github.com/vitest-dev/vitest/pull/3925)
> ```

i agree with @AriPerkkio

**Comment by sheremet-va** [comment]
Yes, let's add it

**Review by AriPerkkio — APPROVED** [review]
Looks good to me. There are also some breaking changes that may come up for custom runner and custom coverage provider implementors. But I don't think those should be mentioned on this migration guide. Tooling developers can check the changes from releases page for more details.

**Pull request merged**
