### PR TITLE
fix(runner): restore leading space in `testNamePattern` (#4103)

### PR DESCRIPTION
**Pull request by segrey**
This reverts commit b5bf32907fae8b8b4508689a32205f94056a721e.

Reverting looks like the most straightforward option to me. Once WebStorm 2024.1 is released, the original commit can simply be merged again.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by segrey** [comment]
@sheremet-va Please let me know if anything is missing.

**Comment by ghiscoding** [comment]
you should probably cc @Dunqing since he is the one who create the commit that you want to revert since he might have a different point of view 😉

**Comment by Dunqing** [comment]
While I would like the two to be compatible, adding it may increase complexity. Reverting is the best solution for now.

**Comment by segrey** [comment]
@ghiscoding Actually, the author of the original commit (@Dunqing) was in the loop from the very beginning (#4103), but I agree that mentioning here wouldn't hurt. No such mistake in #4119 :)

**Pull request merged**
