### PR TITLE
fix(runner): ensure sequential suite overrides sequence.concurrent

### LINKED ISSUE #6652: Regression: When sequence.concurrent is true, tests in a sequential suite run concurrently
### Describe the bug

Original issue report: https://github.com/vitest-dev/vitest/issues/4473

The documentation for [describe.sequential](https://vitest.dev/api/#describe-sequential) states that tests should run sequentially inside a sequential suite when Vitest is run with the [--sequence.concurrent](https://vitest.dev/config/#sequence-concurrent) option enabled, however tests actually run concurrently.

### Reproduction

Run the following tests with the --sequence.concurrent option:

```ts
import { describe, expect, test } from 'vitest';

const delay = (timeout: number) =>
  new Promise((resolve) => setTimeout(resolve, timeout));

let count = 0;

describe.sequential('sequential suite', () => {
  test('test 1', async ({ task }) => {
    await delay(2000);
    expect(task.concurrent).toBeFalsy();
    expect(++count).toBe(1);
  });

  test('test 2', ({ task }) => {
    expect(task.concurrent).toBeFalsy();
    expect(++count).toBe(2);
  });
});
```

The tests pass in Vitest versions 1.0.0 through to 1.6.0, but fail in version 2.0.0 onwards.

https://stackblitz.com/edit/vitest-dev-vitest-yvqmqc?file=package.json,sequential.test.ts

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.34 GB / 31.20 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.4/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 9.12.0 - ~/.nvm/versions/node/v18.20.4/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.70
  npmPackages:
    @vitest/browser: workspace:* => 2.1.2 
    @vitest/coverage-istanbul: workspace:* => 2.1.2 
    @vitest/coverage-v8: workspace:* => 2.1.2 
    @vitest/ui: workspace:* => 2.1.2 
    vite: ^5.4.0 => 5.4.0 
    vitest: workspace:* => 2.1.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by dsyddall**
### Description

Fixes #6652 

Currently, when running Vitest with the `--sequence.concurrent` CLI option or with the `sequence.concurrent` config option set to true, `describe.sequential` has no effect and tests run concurrently.

This PR fixes the issue by ensuring that passing `{ concurrent: false }` to the options of a suite does not only cancel the effect of passing `{ concurrent: true }` but causes `{ sequential: true }` to be set on the options, so that when the value of `options.sequential` is [checked](https://github.com/dsyddall/vitest/blob/eaced8096271a3e83fa283d87b519f672e5bb734/packages/runner/src/suite.ts#L330) in the task function, it overrides the value specified in the runner config.

The test that originally checked for this behaviour became invalid with changes to the runner in Vitest 2.0.0, so this PR also updates the test to correctly check for the behaviour in v2.0.0 onwards.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by hi-ogawa** [comment]
Thanks for the PR!
It looks like your issue went unnoticed since `vi.setConfig({ sequence: { concurrent } })` is not supported properly (type is available but doc says this https://vitest.dev/api/vi.html#vi-setconfig) Can you also add a new test in `test/config` to cover the case like your repro?

**Comment by sheremet-va** [comment]
To me, this seems like a regression. The docs started mentioning it just for clarification purposes, the behaviour of `setConfig` never changed, but how the config is used might've changed. I don't see why it shouldn't work in principle 🤔

**Comment by hi-ogawa** [comment]
Maybe this is because `config.sequence.concurrent` is picked up too early in default suite? https://github.com/vitest-dev/vitest/blob/7a0de0a7c278ce5e542b0e15b7643a6924ef27f5/packages/runner/src/suite.ts#L208-L212

I think this could be delayed until `describe(...)` or `it(...)` are called and at that point we can use `config.sequence.concurrent` overwritten by `vi.setConfig`.

**Comment by dsyddall** [comment]
Okay, that makes sense - in that case, I'll leave the type as it is and I've updated the PR to replace the existing test with a new test in `test/config`, as suggested.

**Review by hi-ogawa — APPROVED** [review]
Thanks, nice tests!

We can investigate `vi.setConfig({ sequence })` separately. I'll create a new issue later.

**Pull request merged**
