### PR TITLE
docs: prefetch avatar images

### PR DESCRIPTION
**Pull request by userquin**
PWA enabled, don't merge yet, I need to do some final tests.

I need to check also the preview, so the PR cannot be on draft.

### CODE REVIEW

**Comment by userquin** [comment]
There is a small problem about sponsors images: since we have not in the sw precache both will be stored on the cache on subsequent navigation and so if we go offline the sponsors will not be loaded.

I can test removing the `loading="lazy" for these 2 images only to check if we can force to include them into the sw cache.

**Comment by userquin** [comment]
@patak-dev with previous hack we still have a problem with your sponsors image, it seems the server is not sending some CORS headers preventing the sw to precache it and maybe some cache headers, while Anthony's sponsors image is ok:

`https://patak.dev/sponsors.svg`
```shell
access-control-allow-origin: *
age: 38874
cache-control: public, max-age=0, must-revalidate
content-disposition: inline; filename="sponsors.svg"
content-encoding: br
content-type: image/svg+xml
date: Sat, 05 Mar 2022 09:38:56 GMT
etag: W/"5aa4d3bcc01a84304b97956f655b0fd042483ef128ac4fb4c10ecf9e3bcced05"
server: Vercel
x-vercel-cache: HIT
x-vercel-id: cdg1::hcgs4-1646473136541-19ed612593c2
```

`https://cdn.jsdelivr.net/gh/antfu/static/sponsors.svg`
```shell
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
age: 6867
cache-control: public, max-age=604800, s-maxage=43200
content-encoding: gzip
content-length: 668467
content-type: image/svg+xml
cross-origin-resource-policy: cross-origin
date: Sat, 05 Mar 2022 09:33:39 GMT
etag: W/"eb786-e8bRIBWb4mnoGfEPBCy+PsLA3h4"
timing-allow-origin: *
vary: Accept-Encoding
x-cache: HIT, HIT
x-content-type-options: nosniff
x-jsd-version: master
x-jsd-version-type: branch
x-served-by: cache-fra19142-FRA, cache-mad22060-MAD
```

**Comment by patak-dev** [comment]
@userquin my sponsor image can now be retrieved using the same scheme as Anthony: https://cdn.jsdelivr.net/gh/patak-dev/static/sponsors.svg

**Comment by antfu** [comment]
Work on it

**Comment by antfu** [comment]
Haha, I think you are think it in a bit more complex way 😅

**Review by antfu — APPROVED** [review]

**Comment by userquin** [comment]
Dont merge yet I need to review it

**Comment by antfu** [comment]
Ouch!

**Comment by antfu** [comment]
I will lock the deploy to the previous build so you can take time to double check

**Comment by userquin** [comment]
I think you have included the sw itself on the sw precache manifest

**Pull request merged**
