### PR TITLE
fix(browser): userEvent.setup initiates a separate state for userEvent instance

### LINKED ISSUE #6082: userEvent.keyboard always releases pressed key with playwright provider
### Describe the bug

I am trying to use the new Interactive API to test the behavior of a button.
It seems that every keyboard command [is automatically released](https://github.com/vitest-dev/vitest/blob/a169d25a922936fabb603173337455ed6d59e86f/packages/browser/src/node/commands/keyboard.ts#L100) even when using the `{Enter>}` syntax.

### Reproduction

https://github.com/edoardocavazza/vitest-keyboard

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 261.33 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.2.1
  npmPackages:
    @vitest/browser: ^2.0.1 => 2.0.1 
    vitest: ^2.0.1 => 2.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Closes #6082

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
@edoardocavazza I am actually not sure about having a global state - it leaks to other tests (I had to add `.setup` to some tests to not break them because previous tests were releasing buttons). What do you think?

**Comment by sheremet-va** [comment]
> Consider this test:

`Shift` will not be released in your example - not before, not after this PR

**Comment by edoardocavazza** [comment]
Sorry, I may have misunderstood the question.
What I wanted to demonstrate with that test is that having a global state may still be necessary to clean the state and avoid leaks in subsequent tests.

**Comment by sheremet-va** [comment]
Yes, I was saying in my previous question that I also found those leaks, but I am not sure what to do with them. Do we resolve them automatically? If you had more tests in between, or `test.each` it would be harder to find why `shift` was pressed, for example. Automatic cleanup might cause unexpected issues because it will call `keyup` handlers that might throw an error, for example.

**Comment by edoardocavazza** [comment]
Ok, now I understand your concerns. My opinion is that however we need to deviate slightly from the functioning of the original library. Automatic cleaning at the end of each test seems to me to be the most desired solution. It should be the developer's responsibility to make sure to clean up the test state by using `afterEach` and deleting added listeners. This is just my preference, but I am open to other solutions.

**Pull request merged**
