### PR TITLE
feat: sveltekit example

### PR DESCRIPTION
**Pull request by PuruVJ**
Sveltekit example. 

Works on Stackblitz too https://stackblitz.com/edit/puruvj-vitest-bbl3di?file=.stackblitzrc (Screenshot thanks to @userquin )
image

ATM, have to use https://github.com/nickbreaton/vitest-svelte-kit because of how sveltekit digests the vite config into itself.

Would love to know maintainers' opinions on using an external lib

### CODE REVIEW

**Comment by patak-dev** [comment]
For references, we discussed in https://chat.vitest.dev, See this [thread]( https://discord.com/channels/917386801235247114/918804871333945394/929824676014854174) and [this discussion](https://github.com/vitest-dev/vitest/discussions/331#discussioncomment-1936712). @benmccann, @dominikg, and others are working to make SvelteKit more friendly to projects like Vitest (making it closer to a Vite plugin instead of a wrapper). Dominik suggested we should wait for this refactor to finish before adding this example to the examples

**Comment by sheremet-va** [comment]
Are there any news for this PR? 😄

**Comment by benmccann** [comment]
We're adding experimental Vitest support to SvelteKit here: https://github.com/sveltejs/kit/pull/5094

**Comment by benmccann** [comment]
`@sveltejs/kit/experimental/vite` [has been released](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next353) in `@sveltejs/kit` version `1.0.0-next.353`. It'd be great if you're able to update this PR to use the new official support. Feedback welcome in https://github.com/sveltejs/kit/issues/5184. Assuming we get a few people giving positive feedback and there are no major issues, we'd like to take it out of experimental before long

**Comment by PuruVJ** [comment]
Happy to update PR.

Im having some git issues, so might close this and open a new PR and link it here

**Comment by PuruVJ** [comment]
https://github.com/vitest-dev/vitest/pull/1542

**Pull request closed without merging**
