### PR TITLE
feat: format test tablename

### PR DESCRIPTION
**Pull request by poyoho**
fix: #2403

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Let’s just use dot notation

**Comment by poyoho** [comment]
emm.. only apply with string temlplate ?

**Comment by sheremet-va** [comment]
> emm.. Do you mean only apply with string temlplate ?

Yeah, I think we should stick with string names: `$name.name.name`

**Comment by poyoho** [comment]
Done!

**Comment by sheremet-va** [comment]
> Done!

Is it? I see `it` still expects a function in this PR. The test name should always be a string, let's not change that. People using current syntax expect `$name.value` to return something, they don't expect to use a function. So if we are implementing this feature, it should be implemented like this:

```ts
it.each`
 name1 | name2
 ${{ val: '1' }} ${{ val: '2' }}
`('val1 - $name1.val, val2 - $name2.val')
```

**Comment by poyoho** [comment]
@sheremet-va done! 😊

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
