### PR TITLE
fix: always use node condition

### LINKED ISSUE #1918: vue-router's useRoute is not correctly mocked
### Describe the bug

When using vitest-suggested testing libraries, I can't successfully mock `useRoute` and `useRouter` from the `vue-router` package.

I'm using:
- jsdom
- @testing-library/vue

Any time I run a component test with a mocked `useRoute`, the mock returns undefined, and Vue warns about missing injections.

```
...
[Vue warn]: injection "Symbol(route location)" not found. 
  at <HelloWorld ref="VTU_COMPONENT" > 
  at <VTUROOT>
...
TypeError: Cannot read properties of undefined (reading 'path')
     19| 
     20|   <div class="card">
     21|     <button type="button" @click="count++">count is {{ count }}</button>
       |                     ^
     22|     <p>
     23|       Edit
```

### Reproduction

See a minimal reproduction, using a fresh `yarn create vite` project here: https://github.com/hidde-jan/vitest-use-route-example/blob/main/src/components/__test__/HelloWorld.test.ts

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.22 MB / 32.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.14.0 - ~/.nodenv/versions/16.14.0/bin/node
    Yarn: 1.22.15 - ~/.nodenv/versions/16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nodenv/versions/16.14.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 102.0.1
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^3.0.3 => 3.0.3 
    vite: ^3.0.7 => 3.0.9 
    vitest: ^0.22.1 => 0.22.1 
```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #1918

### CODE REVIEW

**Comment by antfu** [comment]
Could we include a failing case in the tests or examples?

**Comment by sheremet-va** [comment]
> Could we include a failing case in the tests or examples?

I just wanted to run this against CI. For this to properly work we need a fix in Vite.

**Comment by sheremet-va** [comment]
Tests should be fixed by https://github.com/vitejs/vite/pull/9860

**Review by antfu — DISMISSED** [review]

**Comment by sheremet-va** [comment]
Waiting for release of Vite 3.2

**Pull request merged**
