### PR TITLE
Update App.test.tsx

### PR DESCRIPTION
**Pull request by Polyhistor**
Made a block reusable by placing it inside beforeEach

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
Please fix lint errors

**Comment by Polyhistor** [comment]
sure, will fix those soon

**Comment by Polyhistor** [comment]
sorry got incredibly busy, I will address this pretty soon

**Comment by sheremet-va** [comment]
Doesn't look like this change is needed

**Pull request closed without merging**
