### PR TITLE
feat(ui): add tests summary in the dashboard

### LINKED ISSUE #2022: [Vitest UI] Include the Number of Test/s Passed in the UI Dashboard
### Clear and concise description of the problem

Currently, the test summary that's printed to the terminal includes the number of test/s that passed, and it seems like that Vitest UI dashboard only shows the number of files that passed. 

I believe it would be useful to also include the number of individual tests that passed in the UI dashboard similarly like the terminal summary. 

vite-dashboard
the

### Suggested solution

Include test/s passed in Vitest UI dashboard. 

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by webfansplz**
Closes #2022 

image

### CODE REVIEW

**Comment by userquin** [comment]
@sheremet-va the entry was commented out by Anthony to simplify the dashboard, the PR LGTM maybe @antfu wants to keep it...

**Comment by antfu** [comment]
I was not satisfied with the design and didn't figure out a better way to present it. We could have it if it's really needed, but at least we should make the slashes centered 😅

**Comment by userquin** [comment]
@antfu running the ui locally with current main it looks good:

imagen

imagen

**Comment by userquin** [comment]
maybe small numbers without some entry, I'm reviewing it...

**Comment by userquin** [comment]
@webfansplz can you test commenting out the bg-header container?
```vue
<template>
  <div gap-0 flex="~ col gap-4" h-full justify-center items-center>
    <!-- div bg-header rounded-lg p="y4 x2" -->
    <section aria-labelledby="tests" m="y-4 x-2">
      <TestsEntry />
    </section>
    <TestFilesEntry />
    <!-- /div -->
  </div>
</template>
```

and changing `packages/ui/client/components/dashboard/DashboardEntry.vue` with this one (just changing some attrs to use vertical separators)?

```vue
 <script setup lang="ts">
withDefaults(defineProps<{ tail?: boolean }>(), { tail: false })
</script>

<template>
  <div p-2 text-center flex>
    <div>
      <div text-4xl>
        <slot name="body" />
      </div>
      <div text-md>
        <slot name="header" />
      </div>
    </div>
    <div v-if="!tail" data-testid="tail" my-0 op50 w-2px bg-current origin-center rotate-0 translate-x-3 />
  </div>
</template>
```

**Comment by webfansplz** [comment]
> @webfansplz can you test commenting out the bg-header container?
> 
> ```
> <template>
>   <div gap-0 flex="~ col gap-4" h-full justify-center items-center>
>     
>     <section aria-labelledby="tests" m="y-4 x-2">
>       <TestsEntry />
>     </section>
>     <TestFilesEntry />
>     
>   </div>
> </template>
> ```
> 
> and changing `packages/ui/client/components/dashboard/DashboardEntry.vue` with this one (just changing some attrs to use vertical separators)?
> 
> ```
> <script setup lang="ts">
> withDefaults(defineProps<{ tail?: boolean }>(), { tail: false })
> </script>
> 
> <template>
>   <div p-2 text-center flex>
>     <div>
>       <div text-4xl>
>         <slot name="body" />
>       </div>
>       <div text-md>
>         <slot name="header" />
>       </div>
>     </div>
>     <div v-if="!tail" data-testid="tail" my-0 op50 w-2px bg-current origin-center rotate-0 translate-x-3 />
>   </div>
> </template>
> ```
> 
> imagen

Updated.
image

**Review by userquin — APPROVED** [review]

**Comment by antfu** [comment]
Maybe we just remove the divider and use justify-evenly?

**Comment by userquin** [comment]
imagen

**Comment by userquin** [comment]
@antfu check the capture here: https://streamable.com/rx1i4m

**Pull request merged**
