### PR TITLE
feat: add Marko example and include code coverage for Marko files

### PR DESCRIPTION
**Pull request by DylanPiercey**
### Description

* Adds Marko to the list of supported frameworks (with an example).
* Enables code coverage for Marko files by default.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by sheremet-va — APPROVED** [review]

**Comment by DylanPiercey** [comment]
Rebased, hopefully that's helpful @sheremet-va

**Comment by sheremet-va** [comment]
Marko fails when we try to update dependencies in #5123

Do you have any ideas why might that be?

**Comment by DylanPiercey** [comment]
@sheremet-va could you link the failure? Having a hard time finding it

**Comment by sheremet-va** [comment]
> @sheremet-va could you link the failure? Having a hard time finding it

https://github.com/vitest-dev/vitest/actions/runs/7886477789/job/21519783838?pr=5123

**Comment by sheremet-va** [comment]
> Regenerating the lock file and/or ensuring there are no duplicates of `@babel/types`/`@babel/traverse` will fix it.

Ok, I will try that. Thank you.

**Comment by DylanPiercey** [comment]
@sheremet-va I don't generally use PNPM, but perhaps the [dedupe](https://pnpm.io/cli/dedupe) command would do the trick here?

**Comment by sheremet-va** [comment]
> @sheremet-va I don't generally use PNPM, but perhaps the [dedupe](https://pnpm.io/cli/dedupe) command would do the trick here?

Looks like it's working, thank you 🙏🏻

**Pull request merged**
