### PR TITLE
fix(mock-api): provide an explainatory error message when the mocks API hoisting doesn't work

### LINKED ISSUE #1084: ReferenceError: Cannot access '__vite_ssr_import_0__' before initialization when using mocks
### Describe the bug

I get the `ReferenceError: Cannot access '__vite_ssr_import_0__' before initialization` when i try to use the API `vi.mock`.

### Reproduction

This is a failing workflow: https://github.com/gdorsi/vite-mock-error-repro/runs/5804962645?check_suite_focus=true

This is the test file: https://github.com/gdorsi/vite-mock-error-repro/blob/redaxios/frontend/src/components/LoginForm/LoginForm.test.jsx

This is the repro: https://github.com/gdorsi/vite-mock-error-repro

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 186.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 3.1.1 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 98.0.2
    Safari: 14.1.2
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.0 
    vite: ^2.9.1 => 2.9.1 
    vitest: ^0.8.2 => 0.8.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by gdorsi**
closes #1084

### CODE REVIEW

**Comment by sheremet-va** [comment]
I think it's better to move this to factory evaluation, and check for "ReferenceError". The code is in `mocker.ts`

**Comment by sheremet-va** [comment]
I think it's better to move this to factory evaluation, and check for "ReferenceError". The code is in `mocker.ts`

**Comment by gdorsi** [comment]
Thanks for the review!

Uhm, I'm not sure I fully understand what you mean, this error happens because after the hoising `vi.mock` is called before the `vi` variable declaration.

We never reach the factory evaluation (which happens somewhere around [here](https://github.com/vitest-dev/vitest/blob/b24fb2535991df1f1053973e48c5a7e46b543135/packages/vitest/src/runtime/mocker.ts#L221), right?), because the error is raised at the very start of the module execution.

**Comment by sheremet-va** [comment]
> Thanks for the review!
> 
> Uhm, I'm not sure I fully understand what you mean, this error happens because after the hoising `vi.mock` is called before the `vi` variable declaration.
> 
> We never reach the factory evaluation (which happens somewhere around [here](https://github.com/vitest-dev/vitest/blob/b24fb2535991df1f1053973e48c5a7e46b543135/packages/vitest/src/runtime/mocker.ts#L221), right?), because the error is raised at the very start of the module execution.

Yes, that is why I left a review. I don't like raising the error here, I think better to format an error that actually happens, since parsing is unsafe.

**Comment by gdorsi** [comment]
In this case `callFunctionMock` is never reached.

I've tried to throw an error at the start of the function:

```js
  private async callFunctionMock(dep: string, mock: () => any) {
    throw new Error('callFunctionMock')
```

I still get:
```js
ReferenceError: Cannot access '__vite_ssr_import_0__' before initialization
```

>  I think better to format an error that actually happen

WDYT if we wrap the hoisted statements in a try/catch?

I'm thinking about something like this:

```diff
-     m.prepend(`${m.slice(startIndex, endIndex)}\n`)
+    m.prepend(`try { ${m.slice(startIndex, endIndex)} } catch(err) { isReferenceError(err) ? throw MOCK_ERROR : throw err } \n`)
```

Anyway, if this becomes too complex we could simply close the PR.

**Comment by sheremet-va** [comment]
If it will never be reached, then it shouldn't throw, that's the point.

**Comment by gdorsi** [comment]
I'm still missing the point, sorry 😞 

I think that it throws because the `vi.mock(module)` is executed before the initialization of the `vi` variable.

I wanted to make the error look better than `Cannot access '__vite_ssr_import_0__' before initialization` because it doesn't even mention real the source of the error.

I'm very new to this codebase, so I'm sure I'm missing something big.

**Comment by sheremet-va** [comment]
> I'm still missing the point, sorry 😞
> 
> I think that it throws because the `vi.mock(module)` is executed before the initialization of the `vi` variable.
> 
> I wanted to make the error look better than `Cannot access '__vite_ssr_import_0__' before initialization` because it doesn't even mention real the source of the error.
> 
> I'm very new to this codebase, so I'm sure I'm missing something big.

Oh, wait, you are write. I was thinking about usage inside `factory`, but it will throw on initializing `vi.mock`. Sorry, I got confused!

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
