### PR TITLE
chore(deps): update tinyglobby and use `isDynamicPattern`

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- follow up to https://github.com/vitest-dev/vitest/pull/6502#issuecomment-2383502911

Replaced `isDynamicPattern` with the one from tinyglobby. It also fixes a symlink issue reported by storybook https://github.com/vitest-dev/vitest/pull/6274#issuecomment-2375380966
Thanks @SuperchupuDev for the new release!

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
FYI I've just released a `0.2.8` hotfix 😅 you might want to update to that instead

**Comment by hi-ogawa** [comment]
@SuperchupuDev It looks like this exotic case https://github.com/vitest-dev/vitest/pull/6274#issuecomment-2274472142 came back as failing/timeout? I ran it locally on my Linux PC and this indeed gets stack.

```
pnpm -C test/reporters test custom-reporter -- -t 'load no base'
```

**Comment by SuperchupuDev** [comment]
interesting, i'll take a look tomorrow. meanwhile, can you try to tell me the exact glob usage that makes it get stuck?

**Comment by hi-ogawa** [comment]
@SuperchupuDev I tried a repro but it looks quite puzzling. It's likely that this is related to the scenario like https://github.com/SuperchupuDev/tinyglobby/issues/53, but behavior-wise, it's same as v0.2.6, so maybe something happened internally which is affecting performance of large `node_modules` crawling.

I can only reproduce the difference between `v0.2.6` and `v0.2.8` on Vitest repo's `node_modules`. I added `test/reporters/repro.mjs`, which should stuck only on `v0.2.8`. I hope it would help the investigation.

**Comment by SuperchupuDev** [comment]
i think i know what's going on, node_modules are linked to each other when using pnpm, making `fdir` recursively crawl those. if two packages use each other it probably enters an infinite loop. i wonder how fast-glob handles that

**Comment by SuperchupuDev** [comment]
@hi-ogawa can you tell me if it works using `"tinyglobby": "https://pkg.pr.new/tinyglobby@1f1fa12"` in the package.json? let me know if it does then i'll do a new release

**Comment by hi-ogawa** [comment]
@SuperchupuDev Thanks for quick follow up. I confirmed https://pkg.pr.new/tinyglobby@1f1fa12 is working locally. I'll push it here to check CI now.

**Comment by hi-ogawa** [comment]
> i think i know what's going on, node_modules are linked to each other when using pnpm, making fdir recursively crawl those. if two packages use each other it probably enters an infinite loop. i wonder how fast-glob handles that

Good spot. That might be it since we have a cyclic workspace warning by pnpm like this:

```
$ pnpm i
Scope: all 47 workspace projects
 WARN  There are cyclic workspace dependencies: /home/hiroshi/code/others/vitest/packages/browser, /home/hiroshi/code/others/vitest/packages/vitest
...
```

**Comment by SuperchupuDev** [comment]
great, glad that it works. i've just released `0.2.9` that reverts the symlinks resolution support

**Comment by SuperchupuDev** [comment]
@hi-ogawa fyi i've just released `0.2.10` which adds back symlinks resolution, without a critical bug this time 😅

**Comment by hi-ogawa** [comment]
Closing as per https://github.com/vitest-dev/vitest/pull/6688

**Pull request closed without merging**
