### PR TITLE
fix(cli): parse `--browser=<name>` correctly

### PR DESCRIPTION
**Pull request by AriPerkkio**
### Description

- Fixes https://github.com/vitest-dev/vitest/pull/5126#issuecomment-1937005521

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by hi-ogawa — COMMENTED** [review]
I wonder how these case are handled now.

- `--browser=false`
- `--browser false`
- `--browser some-file.test.ts`

Can you include these in tests?

**Comment by AriPerkkio** [comment]
Added test cases for the `--browser=false` and `--browser false`. Not sure how `--browser some-file.test.ts` could be supported though.

**Comment by hi-ogawa** [comment]
Just to clarify, I wasn't saying to support something like `--browser some-file.test.ts` but I was simply wondering the current and previous behaviors.

I would imagine it would be tricky to support that, so it's probably okay to treat it as `{ name: "some-file.test.ts" }` for now?

**Comment by AriPerkkio** [comment]
Looks like it doesn't work with the latest release either. Let's not do changes related to that for now. I'll revert that test case.

```sh
$ vitest --browser app.spec.ts

 DEV  v1.2.2 /x/y/z/browser-simple
      Browser runner started at http://localhost:5173/


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: [] Browser "app.spec.ts" is not supported by the browser provider "playwright". Supported browsers: firefox, webkit, chromium.
```

**Comment by hi-ogawa** [comment]
Maybe revert `true/false` handling too? It looks like it wasn't supported in the last release.

**Comment by sheremet-va** [comment]
> Maybe revert `true/false` handling too? It looks like it wasn't supported in the last release.

It was clearly a bug, and one of the reasons we are making changes to the CLI parsing is to fix those edge cases.

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
