### PR TITLE
fix: correctly render ansi diff

### LINKED ISSUE #3675: It looks like this change may have caused the output in `@vitest/ui` to print ANSI escape codes.
I commented on #3582 but realized I should probably open a new issue:

It looks like something in #3582 may have caused the output in `@vitest/ui` to print ANSI escape codes.

image

I'm not sure what the root cause is, but I'm sure it started after I upgraded vitest this week.

_Originally posted by @wycats in https://github.com/vitest-dev/vitest/issues/3582#issuecomment-1605079741_

### PR DESCRIPTION
**Pull request by so1ve**
close #3675

### CODE REVIEW

**Comment by so1ve** [comment]
Force pushed for a wrong refactor 😅

**Comment by antfu** [comment]
The lock changes do not seem to needed?

**Comment by so1ve** [comment]
> The lock changes do not seem to needed?

I'm not sure about it. If I don't push it, the ci will fail.

**Comment by sheremet-va** [comment]
CI still fails without it it seems. Please, revert all package-lock changes you made

**Comment by so1ve** [comment]
@sheremet-va Thanks! I've just reverted this change.

**Comment by so1ve** [comment]
I'll create a new branch to avoid unnecessary changes

**Pull request closed without merging**
