### PR TITLE
fix: type issue with spyOn method (fix #2365)

### LINKED ISSUE #2365: Issue with `vi.spyOn` while trying to mock classes
### Describe the bug

I'm getting weird behavior with `vi.spyOn(...).mockImplementation[Once](...)` when spying on a class. I created a minimal example which follows the [example in the docs](https://vitest.dev/guide/mocking.html#cheat-sheet:~:text=have%20returned%20object-,Example%20with%20vi.spyOn,-%3A) almost exactly.

Typescript is giving me an error on the following snippet of code:
```typescript
import * as exports from '../src/foo'
vi.spyOn(exports, 'Foo').mockImplementation(() => {
                         ^ typescript: Property 'mockImplementation' does not exist on type 'never'. [2339]
  const Foo = vi.fn()
  Foo.prototype.hello = vi.fn(() => 'world!')
  return { Foo }
})
```

Vitest happily runs the test anyway and fails with the following error:
```text
TypeError: mock.hello is not a function
 ❯ test/foo.test.ts:13:17
     11|
     12|     const mock = new exports.Foo()
     13|     expect(mock.hello('asdf')).toEqual('hello world!')
       |                 ^
     14|   })
     15| })
```

Not ruling out user error, but I'm fairly certain the test is set up correctly. I even tried a few variations of the mocked function. Typescript says `vi.spyOn(...)` is returning the `never` type, which I think indicates `mockImplementation()` shouldn't be callable and therefore shouldn't cause any side effects. However, the `Foo` class still seems to get modified with the removal of its `hello()` method. I can get around the problem by mocking the entire class, but the docs seem to indicate the repro should work.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-avbfj9?file=test/foo.test.ts

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.16 GB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.1 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 2.4.3 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    vitest: ^0.25.2 => 0.25.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by samkevin1**
I believe the problem was that classes were getting recognized as constructor methods, so it was getting typed incorrectly. Changing the order to check if it's a Class first fixes it.

Related to: #2365

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Can you please add a test case for this?

**Comment by samkevin1** [comment]
Added some test cases @sheremet-va. Can you take a look?

**Review by sheremet-va — APPROVED** [review]

**Review by sheremet-va — CHANGES_REQUESTED** [review]
You have conflicts now, spy was moved into a separate package

**Comment by samkevin1** [comment]
Fixed the conflicts

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
