### PR TITLE
chore: enable isolatedDeclarations in "vitest" package

### PR DESCRIPTION
**Pull request by sheremet-va**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by Dunqing** [comment]
@sxzz Maybe you can help out with this and use your tool (unplugin-isolated-decl)

**Comment by sheremet-va** [comment]
I tried to convert vite-nide, but `transformer: 'oxc'` in `unplugin-isolated-decl` fails on `import type`:

```
[!] RollupError: src/types.ts (1:12): Expected ',', got '{' (Note that you need plugins to import files that are not JavaScript)
src/types.ts (1:12)
1: import type { ViteHotContext } from 'vite/types/hot.js'
               ^
2: import type { EncodedSourceMap } from '@jridgewell/trace-mapping'
3: import type { ModuleCacheMap, ViteNodeRunner } from './client.ts'
```

**Comment by sheremet-va** [comment]
Ok, a few things:
- I added `{ name: 'raw', transform: () => '' }` to silence rollup, but it generated empty entry points
- `unplugin-isolated-decl/rollup` generates every d.ts file, not just the entry points
- `unplugin-isolated-decl/rollup` generates files in the same file structure as the source code instead of putting the close to entry points

**Comment by Dunqing** [comment]
> * `unplugin-isolated-decl/rollup` generates every d.ts file, not just the entry points

Yes, if you need an entry point, you must use it with `rollup-plugin-dts` for now.

**Pull request closed without merging**
