### PR TITLE
fix: load deps reporter

### PR DESCRIPTION
**Pull request by poyoho**
fix: #2245

### CODE REVIEW

**Comment by sheremet-va** [comment]
Doesn't seem like it works? 

It can't work, because `/@fs/` expects absolute path to be after it, and package name is not an absolute path

**Comment by poyoho** [comment]
> Doesn't seem like it works?
> 
> It can't work, because `/@fs/` expects absolute path to be after it, and package name is not an absolute path

hhhh only work in macos 🤦

**Review by AriPerkkio — APPROVED** [review]
Fix verified with bug report's minimal reproduction setup by applying changes under `node_modules/vitest/dist`. Also the added test case seems to trigger the expected condition. Thanks @poyoho! 💯 

However the way how vitest process silently exits in `v0.24.4` is not ideal. I would rather see an error message indicating loading reporter failed. I wonder why this is not visible for users.

https://github.com/vitest-dev/vitest/blob/7f55c54e51be24107d6591761b586dc33890cade/packages/vitest/src/node/reporters/utils.ts#L11-L13

**Comment by sheremet-va** [comment]
I think we can just revert the change altogether (revert #2184 I mean). The problem was with `toFilePath`, and we fixed it by checking existence of folder.

**Comment by poyoho** [comment]
I add the no base on root reporter test case, it seems to work well too. 😊

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
