### PR TITLE
chore: test Vite PR 18329

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

Sourcemap viz of `fixtures/src/Vue/Counter/Counter.vue`

- [before](https://evanw.github.io/source-map-visualization/#MjE0MQBjb25zdCBfX3ZpdGVfc3NyX2ltcG9ydF8wX18gPSBhd2FpdCBfX3ZpdGVfc3NyX2ltcG9ydF9fKCIvQGZzL2hvbWUvaGlyb3NoaS9jb2RlL290aGVycy92aXRlc3Qvbm9kZV9tb2R1bGVzLy5wbnBtL3Z1ZUAzLjQuMzdfdHlwZXNjcmlwdEA1LjUuNC9ub2RlX21vZHVsZXMvdnVlL2luZGV4Lm1qcyIsIHsiaW1wb3J0ZWROYW1lcyI6WyJkZWZpbmVDb21wb25lbnQiLCJyZWYiXX0pOwoKX192aXRlX3Nzcl9leHBvcnRzX18uZGVmYXVsdCA9IF9fdml0ZV9zc3JfaW1wb3J0XzBfXy5kZWZpbmVDb21wb25lbnQoewogIG5hbWU6ICJDb3VudGVyIiwKICBzZXR1cCgpIHsKICAgIGNvbnN0IGNvdW50ID0gX192aXRlX3Nzcl9pbXBvcnRfMF9fLnJlZigwKTsKICAgIHJldHVybiB7IGNvdW50IH07CiAgfSwKICBtZXRob2RzOiB7CiAgICB1bmNvdmVyZWRNZXRob2QoKSB7CiAgICAgIHJldHVybiAiVGhpcyBsaW5lIHNob3VsZCBub3QgYmUgY292ZXJlZCI7CiAgICB9LAogICAgY292ZXJlZE1ldGhvZCgpIHsKICAgICAgcmV0dXJuICJUaGlzIGxpbmUgc2hvdWxkIGJlIGNvdmVyZWQiOwogICAgfSwKICAgIHVuY292ZXJlZE1ldGhvZFVzaW5nSW1wb3J0TWV0YSgpIHsKICAgICAgcmV0dXJuIGBTb3VyY2UgbWFwcyB0ZW5kIHRvIGJyZWFrIHdoZW4gaW1wb3J0IG1ldGEgaXMgdXNlZDogJHtfX3ZpdGVfc3NyX2ltcG9ydF9tZXRhX18uZW52LkJBU0VfVVJMfWA7CiAgICB9CiAgfQp9KTsKCi8vIyBzb3VyY2VNYXBwaW5nU291cmNlPXZpdGUtbm9kZQovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247Y2hhcnNldD11dGYtODtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnRZWEJ3YVc1bmN5STZJa0ZCUVVFc1EwRkJRVHRCUVVGeFF6dEJRVVZ5UXl3clFrRkJaU3h6UTBGQlowSTdRVUZCUVN4RlFVTTNRaXhOUVVGTk8wRkJRVUVzUlVGRlRpeFJRVUZSTzBGQlEwNHNWVUZCVFN4UlFVRlJMREJDUVVGSkxFTkJRVU03UVVGRGJrSXNWMEZCVHl4RlFVRkZMRTFCUVUwN1FVRkJRU3hGUVVOcVFqdEJRVUZCTEVWQlJVRXNVMEZCVXp0QlFVRkJMRWxCUTFBc2EwSkJRV3RDTzBGQlEyaENMR0ZCUVU4N1FVRkJRU3hKUVVOVU8wRkJRVUVzU1VGRlFTeG5Ra0ZCWjBJN1FVRkRaQ3hoUVVGUE8wRkJRVUVzU1VGRFZEdEJRVUZCTEVsQlJVRXNhVU5CUVdsRE8wRkJReTlDTEdGQlFVOHNkVVJCUVhWRUxEWkNRVUZuUWl4UlFVRlJPMEZCUVVFc1NVRkRlRVk3UVVGQlFTeEZRVU5HTzBGQlEwWXNRMEZCUXlJc0ltNWhiV1Z6SWpwYlhTd2lhV2R1YjNKbFRHbHpkQ0k2VzEwc0luTnZkWEpqWlhNaU9sc2lRMjkxYm5SbGNpNWpiMjF3YjI1bGJuUXVkSE1pWFN3aWMyOTFjbU5sYzBOdmJuUmxiblFpT2xzaWFXMXdiM0owSUhzZ1pHVm1hVzVsUTI5dGNHOXVaVzUwTENCeVpXWWdmU0JtY205dElDZDJkV1VuWEc1Y2JtVjRjRzl5ZENCa1pXWmhkV3gwSUdSbFptbHVaVU52YlhCdmJtVnVkQ2g3WEc0Z0lHNWhiV1U2SUNkRGIzVnVkR1Z5Snl4Y2JseHVJQ0J6WlhSMWNDZ3BJSHRjYmlBZ0lDQmpiMjV6ZENCamIzVnVkQ0E5SUhKbFppZ3dLVnh1SUNBZ0lISmxkSFZ5YmlCN0lHTnZkVzUwSUgxY2JpQWdmU3hjYmx4dUlDQnRaWFJvYjJSek9pQjdYRzRnSUNBZ2RXNWpiM1psY21Wa1RXVjBhRzlrS0NrZ2UxeHVJQ0FnSUNBZ2NtVjBkWEp1SUNkVWFHbHpJR3hwYm1VZ2MyaHZkV3hrSUc1dmRDQmlaU0JqYjNabGNtVmtKMXh1SUNBZ0lIMHNYRzVjYmlBZ0lDQmpiM1psY21Wa1RXVjBhRzlrS0NrZ2UxeHVJQ0FnSUNBZ2NtVjBkWEp1SUNkVWFHbHpJR3hwYm1VZ2MyaHZkV3hrSUdKbElHTnZkbVZ5WldRblhHNGdJQ0FnZlN4Y2JseHVJQ0FnSUhWdVkyOTJaWEpsWkUxbGRHaHZaRlZ6YVc1blNXMXdiM0owVFdWMFlTZ3BJSHRjYmlBZ0lDQWdJSEpsZEhWeWJpQmdVMjkxY21ObElHMWhjSE1nZEdWdVpDQjBieUJpY21WaGF5QjNhR1Z1SUdsdGNHOXlkQ0J0WlhSaElHbHpJSFZ6WldRNklDUjdhVzF3YjNKMExtMWxkR0V1Wlc1MkxrSkJVMFZmVlZKTWZXQmNiaUFnSUNCOUxGeHVJQ0I5TEZ4dWZTbGNiaUpkTENKbWFXeGxJam9pTDJacGVIUjFjbVZ6TDNOeVl5OVdkV1V2UTI5MWJuUmxjaTlEYjNWdWRHVnlMbU52YlhCdmJtVnVkQzUwY3o5MmRXVW1kSGx3WlQxelkzSnBjSFFtYzNKalBYUnlkV1VtYkdGdVp5NTBjeUo5Cjk5MAB7InZlcnNpb24iOjMsIm1hcHBpbmdzIjoiQUFBQSxDQUFBO0FBQXFDO0FBRXJDLCtCQUFlLHNDQUFnQjtBQUFBLEVBQzdCLE1BQU07QUFBQSxFQUVOLFFBQVE7QUFDTixVQUFNLFFBQVEsMEJBQUksQ0FBQztBQUNuQixXQUFPLEVBQUUsTUFBTTtBQUFBLEVBQ2pCO0FBQUEsRUFFQSxTQUFTO0FBQUEsSUFDUCxrQkFBa0I7QUFDaEIsYUFBTztBQUFBLElBQ1Q7QUFBQSxJQUVBLGdCQUFnQjtBQUNkLGFBQU87QUFBQSxJQUNUO0FBQUEsSUFFQSxpQ0FBaUM7QUFDL0IsYUFBTyx1REFBdUQsNkJBQWdCLFFBQVE7QUFBQSxJQUN4RjtBQUFBLEVBQ0Y7QUFDRixDQUFDIiwibmFtZXMiOltdLCJpZ25vcmVMaXN0IjpbXSwic291cmNlcyI6WyJDb3VudGVyLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgbmFtZTogJ0NvdW50ZXInLFxuXG4gIHNldHVwKCkge1xuICAgIGNvbnN0IGNvdW50ID0gcmVmKDApXG4gICAgcmV0dXJuIHsgY291bnQgfVxuICB9LFxuXG4gIG1ldGhvZHM6IHtcbiAgICB1bmNvdmVyZWRNZXRob2QoKSB7XG4gICAgICByZXR1cm4gJ1RoaXMgbGluZSBzaG91bGQgbm90IGJlIGNvdmVyZWQnXG4gICAgfSxcblxuICAgIGNvdmVyZWRNZXRob2QoKSB7XG4gICAgICByZXR1cm4gJ1RoaXMgbGluZSBzaG91bGQgYmUgY292ZXJlZCdcbiAgICB9LFxuXG4gICAgdW5jb3ZlcmVkTWV0aG9kVXNpbmdJbXBvcnRNZXRhKCkge1xuICAgICAgcmV0dXJuIGBTb3VyY2UgbWFwcyB0ZW5kIHRvIGJyZWFrIHdoZW4gaW1wb3J0IG1ldGEgaXMgdXNlZDogJHtpbXBvcnQubWV0YS5lbnYuQkFTRV9VUkx9YFxuICAgIH0sXG4gIH0sXG59KVxuIl0sImZpbGUiOiIvZml4dHVyZXMvc3JjL1Z1ZS9Db3VudGVyL0NvdW50ZXIuY29tcG9uZW50LnRzP3Z1ZSZ0eXBlPXNjcmlwdCZzcmM9dHJ1ZSZsYW5nLnRzIn0=)
- [after](https://evanw.github.io/source-map-visualization/#MjIyOQBjb25zdCBfX3ZpdGVfc3NyX2lkZW50aXR5X18gPSB2ID0+IHY7CmNvbnN0IF9fdml0ZV9zc3JfaW1wb3J0XzBfXyA9IGF3YWl0IF9fdml0ZV9zc3JfaW1wb3J0X18oIi9AZnMvaG9tZS9oaXJvc2hpL2NvZGUvb3RoZXJzL3ZpdGVzdC9ub2RlX21vZHVsZXMvLnBucG0vdnVlQDMuNC4zN190eXBlc2NyaXB0QDUuNS40L25vZGVfbW9kdWxlcy92dWUvaW5kZXgubWpzIiwgeyJpbXBvcnRlZE5hbWVzIjpbImRlZmluZUNvbXBvbmVudCIsInJlZiJdfSk7CgpfX3ZpdGVfc3NyX2V4cG9ydHNfXy5kZWZhdWx0ID0gX192aXRlX3Nzcl9pZGVudGl0eV9fKF9fdml0ZV9zc3JfaW1wb3J0XzBfXy5kZWZpbmVDb21wb25lbnQpKHsKICBuYW1lOiAiQ291bnRlciIsCiAgc2V0dXAoKSB7CiAgICBjb25zdCBjb3VudCA9IF9fdml0ZV9zc3JfaWRlbnRpdHlfXyhfX3ZpdGVfc3NyX2ltcG9ydF8wX18ucmVmKSgwKTsKICAgIHJldHVybiB7IGNvdW50IH07CiAgfSwKICBtZXRob2RzOiB7CiAgICB1bmNvdmVyZWRNZXRob2QoKSB7CiAgICAgIHJldHVybiAiVGhpcyBsaW5lIHNob3VsZCBub3QgYmUgY292ZXJlZCI7CiAgICB9LAogICAgY292ZXJlZE1ldGhvZCgpIHsKICAgICAgcmV0dXJuICJUaGlzIGxpbmUgc2hvdWxkIGJlIGNvdmVyZWQiOwogICAgfSwKICAgIHVuY292ZXJlZE1ldGhvZFVzaW5nSW1wb3J0TWV0YSgpIHsKICAgICAgcmV0dXJuIGBTb3VyY2UgbWFwcyB0ZW5kIHRvIGJyZWFrIHdoZW4gaW1wb3J0IG1ldGEgaXMgdXNlZDogJHtfX3ZpdGVfc3NyX2ltcG9ydF9tZXRhX18uZW52LkJBU0VfVVJMfWA7CiAgICB9CiAgfQp9KTsKCi8vIyBzb3VyY2VNYXBwaW5nU291cmNlPXZpdGUtbm9kZQovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247Y2hhcnNldD11dGYtODtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnRZWEJ3YVc1bmN5STZJa0ZCUVVFc1EwRkJRVHM3UVVGQmNVTTdRVUZGY2tNc2NVUkJRV1VzZFVOQlFXZENPMEZCUVVFc1JVRkROMElzVFVGQlRUdEJRVUZCTEVWQlJVNHNVVUZCVVR0QlFVTk9MRlZCUVUwc09FSkJRVkVzTWtKQlFVa3NRMEZCUXp0QlFVTnVRaXhYUVVGUExFVkJRVVVzVFVGQlRUdEJRVUZCTEVWQlEycENPMEZCUVVFc1JVRkZRU3hUUVVGVE8wRkJRVUVzU1VGRFVDeHJRa0ZCYTBJN1FVRkRhRUlzWVVGQlR6dEJRVUZCTEVsQlExUTdRVUZCUVN4SlFVVkJMR2RDUVVGblFqdEJRVU5rTEdGQlFVODdRVUZCUVN4SlFVTlVPMEZCUVVFc1NVRkZRU3hwUTBGQmFVTTdRVUZETDBJc1lVRkJUeXgxUkVGQmRVUXNOa0pCUVdkQ0xGRkJRVkU3UVVGQlFTeEpRVU40Ump0QlFVRkJMRVZCUTBZN1FVRkRSaXhEUVVGRElpd2libUZ0WlhNaU9sdGRMQ0pwWjI1dmNtVk1hWE4wSWpwYlhTd2ljMjkxY21ObGN5STZXeUpEYjNWdWRHVnlMbU52YlhCdmJtVnVkQzUwY3lKZExDSnpiM1Z5WTJWelEyOXVkR1Z1ZENJNld5SnBiWEJ2Y25RZ2V5QmtaV1pwYm1WRGIyMXdiMjVsYm5Rc0lISmxaaUI5SUdaeWIyMGdKM1oxWlNkY2JseHVaWGh3YjNKMElHUmxabUYxYkhRZ1pHVm1hVzVsUTI5dGNHOXVaVzUwS0h0Y2JpQWdibUZ0WlRvZ0owTnZkVzUwWlhJbkxGeHVYRzRnSUhObGRIVndLQ2tnZTF4dUlDQWdJR052Ym5OMElHTnZkVzUwSUQwZ2NtVm1LREFwWEc0Z0lDQWdjbVYwZFhKdUlIc2dZMjkxYm5RZ2ZWeHVJQ0I5TEZ4dVhHNGdJRzFsZEdodlpITTZJSHRjYmlBZ0lDQjFibU52ZG1WeVpXUk5aWFJvYjJRb0tTQjdYRzRnSUNBZ0lDQnlaWFIxY200Z0oxUm9hWE1nYkdsdVpTQnphRzkxYkdRZ2JtOTBJR0psSUdOdmRtVnlaV1FuWEc0Z0lDQWdmU3hjYmx4dUlDQWdJR052ZG1WeVpXUk5aWFJvYjJRb0tTQjdYRzRnSUNBZ0lDQnlaWFIxY200Z0oxUm9hWE1nYkdsdVpTQnphRzkxYkdRZ1ltVWdZMjkyWlhKbFpDZGNiaUFnSUNCOUxGeHVYRzRnSUNBZ2RXNWpiM1psY21Wa1RXVjBhRzlrVlhOcGJtZEpiWEJ2Y25STlpYUmhLQ2tnZTF4dUlDQWdJQ0FnY21WMGRYSnVJR0JUYjNWeVkyVWdiV0Z3Y3lCMFpXNWtJSFJ2SUdKeVpXRnJJSGRvWlc0Z2FXMXdiM0owSUcxbGRHRWdhWE1nZFhObFpEb2dKSHRwYlhCdmNuUXViV1YwWVM1bGJuWXVRa0ZUUlY5VlVreDlZRnh1SUNBZ0lIMHNYRzRnSUgwc1hHNTlLVnh1SWwwc0ltWnBiR1VpT2lJdlptbDRkSFZ5WlhNdmMzSmpMMVoxWlM5RGIzVnVkR1Z5TDBOdmRXNTBaWEl1WTI5dGNHOXVaVzUwTG5SelAzWjFaU1owZVhCbFBYTmpjbWx3ZENaemNtTTlkSEoxWlNac1lXNW5MblJ6SW4wPQo5OTIAeyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQUEsQ0FBQTs7QUFBcUM7QUFFckMscURBQWUsdUNBQWdCO0FBQUEsRUFDN0IsTUFBTTtBQUFBLEVBRU4sUUFBUTtBQUNOLFVBQU0sOEJBQVEsMkJBQUksQ0FBQztBQUNuQixXQUFPLEVBQUUsTUFBTTtBQUFBLEVBQ2pCO0FBQUEsRUFFQSxTQUFTO0FBQUEsSUFDUCxrQkFBa0I7QUFDaEIsYUFBTztBQUFBLElBQ1Q7QUFBQSxJQUVBLGdCQUFnQjtBQUNkLGFBQU87QUFBQSxJQUNUO0FBQUEsSUFFQSxpQ0FBaUM7QUFDL0IsYUFBTyx1REFBdUQsNkJBQWdCLFFBQVE7QUFBQSxJQUN4RjtBQUFBLEVBQ0Y7QUFDRixDQUFDIiwibmFtZXMiOltdLCJpZ25vcmVMaXN0IjpbXSwic291cmNlcyI6WyJDb3VudGVyLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgbmFtZTogJ0NvdW50ZXInLFxuXG4gIHNldHVwKCkge1xuICAgIGNvbnN0IGNvdW50ID0gcmVmKDApXG4gICAgcmV0dXJuIHsgY291bnQgfVxuICB9LFxuXG4gIG1ldGhvZHM6IHtcbiAgICB1bmNvdmVyZWRNZXRob2QoKSB7XG4gICAgICByZXR1cm4gJ1RoaXMgbGluZSBzaG91bGQgbm90IGJlIGNvdmVyZWQnXG4gICAgfSxcblxuICAgIGNvdmVyZWRNZXRob2QoKSB7XG4gICAgICByZXR1cm4gJ1RoaXMgbGluZSBzaG91bGQgYmUgY292ZXJlZCdcbiAgICB9LFxuXG4gICAgdW5jb3ZlcmVkTWV0aG9kVXNpbmdJbXBvcnRNZXRhKCkge1xuICAgICAgcmV0dXJuIGBTb3VyY2UgbWFwcyB0ZW5kIHRvIGJyZWFrIHdoZW4gaW1wb3J0IG1ldGEgaXMgdXNlZDogJHtpbXBvcnQubWV0YS5lbnYuQkFTRV9VUkx9YFxuICAgIH0sXG4gIH0sXG59KVxuIl0sImZpbGUiOiIvZml4dHVyZXMvc3JjL1Z1ZS9Db3VudGVyL0NvdW50ZXIuY29tcG9uZW50LnRzP3Z1ZSZ0eXBlPXNjcmlwdCZzcmM9dHJ1ZSZsYW5nLnRzIn0=)

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by AriPerkkio — CHANGES_REQUESTED** [review]
@hi-ogawa could you try if commenting out this part fixes the coverage? The new helper method added by Vite is on first line so I wonder if that's breaking here. 

https://github.com/vitest-dev/vitest/blob/c4076e64cfb06ae6322c20260a13d1e932f0100e/packages/vite-node/src/source-map.ts#L64-L68

**Comment by hi-ogawa** [comment]
@AriPerkkio  Good find! Commenting out that mapping fixed the issue. There is a diff in `lines` and `statements`, but I can see the same diff on main when I comment out the same line, so I suppose it's been affecting the coverage already.

I guess we need to find a different way to make inspect-brk work.

**Comment by hi-ogawa** [comment]
For example, currently the first line `<script setup lang="ts">` is considered covered:

- https://htmlpreview.github.io/?https://raw.githubusercontent.com/hi-ogawa/vitest/chore-vite-ssr-identity/test/coverage-test/coverage-now/Vue/Defined.vue.html

but it's removed after removing first line mapping:

- https://htmlpreview.github.io/?https://raw.githubusercontent.com/hi-ogawa/vitest/chore-vite-ssr-identity/test/coverage-test/coverage-18329-x/Vue/Defined.vue.html

**Comment by AriPerkkio** [comment]
> I guess we need to find a different way to make inspect-brk work.

I think for now it would be enough to set this breakpoint when we detect that `vitest --inspect-brk` is used.

**Comment by hi-ogawa** [comment]
Closing in favor of https://github.com/vitest-dev/vitest/pull/6732

**Pull request closed without merging**
