### PR TITLE
perf: do not resolve static import since it's already resolved

### PR DESCRIPTION
**Pull request by sheremet-va**
All imports in `__vite_ssr_import__` should already be resolved, so we don't need to resolve it again.

It's possible that import in `__vite_ssr_dynamic_import__` is not resolved, so we still need to resolve it. @patak-dev do you think it's possible to provide information in `__vite_ssr_dynamic_import__` if import is static or dynamic? Something like this:

```ts
__vite_ssr_dynamic_import__('/path/to/file.ts', { resolved: true })
__vite_ssr_dynamic_import__(someVariable, { resolved: false })
```

### CODE REVIEW

**Comment by patak-dev** [comment]
In Vite, it seems we only need to resolve them when the path is relative. See https://github.com/vitejs/vite/blob/d814d6c56765696f766b32b5fce604acf715bf3c/packages/vite/src/node/ssr/ssrModuleLoader.ts#L181
Maybe doing the same here would work?

**Comment by sheremet-va** [comment]
> In Vite, it seems we only need to resolve them when the path is relative. See [vitejs/vite@`d814d6c`/packages/vite/src/node/ssr/ssrModuleLoader.ts#L181](https://github.com/vitejs/vite/blob/d814d6c56765696f766b32b5fce604acf715bf3c/packages/vite/src/node/ssr/ssrModuleLoader.ts#L181)
> Maybe doing the same here would work?

It would mean that people cannot do this:

```ts
const filepath = condition ? '@/src/a.ts' : '@/src/b.ts'
await import(filepath)
```

**Comment by patak-dev** [comment]
Is `@` an alias there? Does this work in Vite? I think it may be ok to say that this kind of completely dynamic file path needs to be resolved already by the user 🤔

**Comment by sheremet-va** [comment]
> Is `@` an alias there? Does this work in Vite? I think it may be ok to say that this kind of completely dynamic file path needs to be resolved already by the user 🤔

It doesn't work in Vite, but it does work in vite-node which is a feature.

**Comment by patak-dev** [comment]
I see. Two ideas. Is the id already added to the module graph at this point? Maybe a way to see if it has been resolved is to check if `moduleGraph.getModuleById(id)` returns a module? 
@antfu maybe you'll know better here if we should move this as a feature request to Vite core.

**Comment by sheremet-va** [comment]
> I see. Is the id already added to the module graph at this point? Maybe a way to see if it has been resolved is to check if `moduleGraph.getModuleById(id)` returns a module?
> @antfu maybe you'll know better here if we should move this as a feature request to Vite core.

module graph stores modules only by their filepath in vite-node. And it's possible that it's not there yet.

**Comment by sheremet-va** [comment]
Turns out we still need to resolve url for external modules (Vite does this in `nodeImport` function)

**Pull request closed without merging**
