### PR TITLE
test: adding graphql API server mock

### PR DESCRIPTION
**Pull request by Sajad-Sharhani**

### CODE REVIEW

**Comment by mitchelvanbever** [comment]
Not sure if we should make it a seperate test folder. I think it's pretty similar to what tiger is doing, it's just that there is a different handler added to the mocks. Any specific reason you chose to go this route?

**Comment by Sajad-Sharhani** [comment]
I build it based on [](https://github.com/mswjs/examples) in which they separate rest from graphql api

**Comment by mitchelvanbever** [comment]
> I build it based on [mswjs/examples](https://github.com/mswjs/examples) in which they separate rest from graphql API examples

Fair enough. I think the only reason they are separating them is because of the different dependencies between the two and most likely someone who is looking to mock requests will either needs REST or GraphQL (usually not both). I do however feel in our case, adding yet another folder would convolute the example directory a lot (also keeping in mind there might be more MSW examples to come). And this would ultimately make it less clear where to find the example for the type of network mocking you need. 

For now it would make more sense to me to combine the examples to keep the MSW examples clear and concise. Would you mind adding it into the other example or do you have strong arguments against it? 🙂  

p.s; Let me know if you need some inspiration on how to make a clear division between the different network types in the test if you do want to move the examples

**Comment by Sajad-Sharhani** [comment]
> 

what u saying makes sense and I will do it
thank u for the help  and will be in touch if I had any question

**Comment by antfu** [comment]
Convert to draft as the tests are failing.

**Comment by Sajad-Sharhani** [comment]
this PR failed I will try new PR soon

**Pull request closed without merging**
