### PR TITLE
feat(ui): add coverage

### LINKED ISSUE #2336: Coverage viewer in Vitest UI
### Clear and concise description of the problem

As a developer building tests using Vitest I want to keep an eye on the test coverage to make sure I'm hitting all the code paths I want to test so that I can write extra tests should coverage not be sufficient.

Currently in Vitest UI there is no information about code coverage visible except the coverage information in the CLI, which is not very detailed.

image

### Suggested solution

My proposal is a new tab or section in the Vitest UI that shows a project's source code and the coverage like Istanbul would render in their HTML output.

image

With maybe a bit of styling to fit the Vitest UI theme ;)

### Alternative

- The UI could also host the Istanbul coverage HTML files from the `coverage` folder whenever Vitest UI is running. Perhaps a button in the Vitest UI could link to the coverage pages.

- My current 'alternative' is to start a web server through my IDE that hosts the `coverage` folder and I have that open in another browser tab. Opening `coverage/index.html` directly in the browser also works, but then it does not auto-update like it does when hosting through VSCode.

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by userquin**
This PR adds the coverage folder in a new iframe inside `Coverage` component:
- coverage css files not being served
- vite tranforms coverage html pages, I need to find a way to exclude them
- fix coverage error (check the screenshot below): I guess the error comes when Vite injects `@vite/client` script

To test the coverage run `pnpm run build && pnpm run test` from root folder and from another shell run `cd packages/ui && nr dev:ui`.

/cc @edimitchel : from your comment here https://github.com/vitest-dev/vitest/pull/493#issuecomment-1012659202

closes #2336 

imagen

### CODE REVIEW

**Comment by userquin** [comment]
It is working but only with bundled ui, using it on dev I cannot make it working (css not being loaded):
- `pnpm run install && pnpm run build` from root
- `cd test/core && pnpm vitest --ui`

We also need to disable coverage button while running and adding small delay once tests run finish.

The css styles using `istambul` in dark mode needs a review: https://streamable.com/8jsoac

**Comment by userquin** [comment]
Lastest changes: https://streamable.com/3ek8l0

**Comment by userquin** [comment]
I need to add another script to enable coverage, rn enabled in tests/core.

**Comment by edimitchel** [comment]
I wondering, won't you able to reuse raw data and attach coverage information to each test suite and show the coverage on suite/test items list, and details put in a test details tab?

**Comment by userquin** [comment]
> I wondering, won't you able to reuse raw data and attach coverage information to each test suite and show the coverage on suite/test items list, and details put in a test details tab?

Yeah, I'll work next weekend on this - current state was simple, just adding a middleware and some client stuff, your proposal requires a bit more work

**Pull request closed without merging**
