### PR TITLE
feat: findRelatedTests flag, to run only changed tests

### PR DESCRIPTION
**Pull request by sheremet-va**
Related: https://github.com/vitest-dev/vitest/issues/280

CAC allows passing array as an argument only if you repeat option, like: 
```
vitest --findRelatedTests src/timeout.ts --findRelatedTests src/mockedA.ts
```

I personally think jest's way (using space as separator) is more convinient

### CODE REVIEW

**Comment by antfu** [comment]
We could use comma and split it ourselfs

**Comment by sheremet-va** [comment]
> We could use comma and split it ourselves

Still not ideal. I like space and think we could need it in the future because `*/**` syntax returns files separated by space.

**Comment by sheremet-va** [comment]
Also I think most of the people using this feature have it configured the same for `eslint` and other tools that support passing files.

**Comment by antfu** [comment]
idk, won't that have an ambiguous issue to distinguish from options args or command args?

**Comment by sheremet-va** [comment]
> idk, won't that have an ambiguous issue to distinguish from options args or command args?

In what way? Maybe it's harder for parser, but I think it looks more native to the human eye, no?

**Comment by sheremet-va** [comment]
> > idk, won't that have an ambiguous issue to distinguish from options args or command args?
> 
> In what way? Maybe it's harder for parser, but I think it looks more native to the human eye, no?

Maybe we should ask in Discord

**Comment by antfu** [comment]
```ts
vite run basic
```

```ts
vite run --global basic
```

```ts
vite run --global --repoter dot basic
```

```ts
vite run --global --repoter dot --findRelatedTests src/timeout.ts src/mockedA.ts basic
```

**Comment by sheremet-va** [comment]
> ```ts
> vite run basic
> ```
> 
> ```ts
> vite run --global basic
> ```
> 
> ```ts
> vite run --global --repoter dot basic
> ```
> 
> ```ts
> vite run --global --repoter dot --findRelatedTests src/timeout.ts src/mockedA.ts basic
> ```

Should placing options before arguments be allowed tho?

Yargs for example [can parse it](https://github.com/yargs/yargs/blob/HEAD/docs/api.md#arraykey)

**Pull request merged**
