### PR TITLE
feat: mocking timers with sinon

### LINKED ISSUE #506: support for fake clock (`new Date()`, `Date.now()`...) in vitest timers
### Clear and concise description of the problem

Jest support for timers has builtin support for clocks: when using `jest.useFakeTimers()`, a fake clock is instantiated. Then calls to `jest.advanceTimersByTime()` increase the fake clock time. Application code that use `new Date()`, or `Date.now()`, or `performance.now()` and others will get this fake time.

Jest leverages `@sinonjs/fake-timers` to do so (in its `modern` implementation, which is the default nowadays).

It would be super handy to have vitest do the same. Currently the API mimicks the one from Jest (which is awesome, don't get me wrong :hugs:) but doesn't handle this feature, which makes a test suite migration a bit more difficult, as tests that rely on `setTimeout` or`setInterval` will behave the same in vitest and Jest, but the one that leverage `Date` will not.

### Suggested solution

It could be possible to do the same as Jest and directly leverage `@sinonjs/fake-timers`.

### Alternative

It is possible for a developer who wants to have a fake clock in its test to use `@sinonjs/fake-timers` in addition to vitest

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
Closes #506

Mockdate removed, since mocking `Date` objects can be done with `setSystemTime`

@antfu also I'm not sure, does inlining happens automatically?

THIS IS BREAKING CHANGE SINCE IT REMOVES `mockCurrentDate` - use `setSystemTime` instead!

### CODE REVIEW

**Comment by Smrtnyk** [comment]
amazing work

**Comment by fadi-george** [comment]
I get errors w/ old vi pending timers, I hope this will fix it.

**Comment by antfu** [comment]
We can release 0.2 with this after the conflict fixed

**Comment by sheremet-va** [comment]
> We can release 0.2 with this after the conflict fixed

Merge conflicts fixed

**Review by antfu — APPROVED** [review]

**Pull request merged**
