### PR TITLE
Fix: do not add expected/actual attributes in a object when does not exist

### PR DESCRIPTION
**Pull request by 11joselu**
When we parse a Error object without expected or actual. `processError` add any of both attributes with `'undefined'` as a value.

### CODE REVIEW

**Review by sheremet-va — APPROVED** [review]

**Comment by JoostK** [comment]
FYI this breaks some stuff:

```
TypeError: Cannot read properties of null (reading 'split')
    at Diff.lineDiff.tokenize (node_modules/vitest/dist/diff-711cddf1.js:311:32)
    at Diff.diff (node_modules/vitest/dist/diff-711cddf1.js:32:39)
    at diffLines (node_modules/vitest/dist/diff-711cddf1.js:336:19)
    at structuredPatch (node_modules/vitest/dist/diff-711cddf1.js:508:14)
    at createTwoFilesPatch (node_modules/vitest/dist/diff-711cddf1.js:656:22)
    at createPatch (node_modules/vitest/dist/diff-711cddf1.js:659:10)
    at unifiedDiff (node_modules/vitest/dist/diff-711cddf1.js:4717:15)
    at displayDiff (node_modules/vitest/dist/diff-711cddf1.js:4627:24)
    at printError (node_modules/vitest/dist/diff-711cddf1.js:4596:5)
    at async DefaultReporter.printTaskErrors (node_modules/vitest/dist/index-05648ba5.js:7107:7)
```

**Comment by 11joselu** [comment]
> FYI this breaks some stuff:
> 
> ```
> TypeError: Cannot read properties of null (reading 'split')
>     at Diff.lineDiff.tokenize (node_modules/vitest/dist/diff-711cddf1.js:311:32)
>     at Diff.diff (node_modules/vitest/dist/diff-711cddf1.js:32:39)
>     at diffLines (node_modules/vitest/dist/diff-711cddf1.js:336:19)
>     at structuredPatch (node_modules/vitest/dist/diff-711cddf1.js:508:14)
>     at createTwoFilesPatch (node_modules/vitest/dist/diff-711cddf1.js:656:22)
>     at createPatch (node_modules/vitest/dist/diff-711cddf1.js:659:10)
>     at unifiedDiff (node_modules/vitest/dist/diff-711cddf1.js:4717:15)
>     at displayDiff (node_modules/vitest/dist/diff-711cddf1.js:4627:24)
>     at printError (node_modules/vitest/dist/diff-711cddf1.js:4596:5)
>     at async DefaultReporter.printTaskErrors (node_modules/vitest/dist/index-05648ba5.js:7107:7)
> ```

Can you give me a reproducible example please?

**Comment by userquin** [comment]
@11joselu should be fixed on linked PR 409

**Comment by 11joselu** [comment]
> @11joselu should be fixed on linked PR 409

Nice catch. Thank you!!

**Pull request merged**
