### PR TITLE
fix: failing test with React is not defined

### PR DESCRIPTION
**Pull request by Aslemammad**
failing test for #261 by @fadi-george

### CODE REVIEW

**Comment by Aslemammad** [comment]
My guess is that vitest doesn't respect the esbuild inject, so that's why react is not defined, maybe :eyes:

**Comment by Aslemammad** [comment]
the problem doesn't happen with basic.test.tsx
because it recognizes react, but in Fetcher.tsx, transformRequest gives us this
```js
"const __vite_ssr_import_0__ = await __vite_ssr_import__("/@fs/home/bagher/vitest/node_modules/.pnpm/react@17.0.2/node_modules/react/index.js");
const Fetcher = ({
  children,
  loader = /* @__PURE__ */ React.createElement("div", null, "Loading...")
}) => {
  const loading = false;
  const data = [];
  if (loading)
    return loader;
  return children(data);
};
__vite_ssr_exports__.default = Fetcher;
"
```

**Comment by Aslemammad** [comment]
i'll continue investigating this tomorrow!

**Comment by antfu** [comment]
Why not use the react plugin?

**Comment by Aslemammad** [comment]
I am away from the pc, but you can try it and see if it passes, if yes, feel free to close. 
i can do that tomorrow if u want.

**Comment by Aslemammad** [comment]
react plugin doesn't solve the issue!

**Comment by antfu** [comment]
We have a few working React examples already, I don't understand what's the problem this PR is trying to solve

**Comment by Aslemammad** [comment]
For now, it's not solving anything, but it tries to add a simple example that fails when we use a tag as a default value for a parameter (jsx value) or a type that uses that is `React` type as a parent.
like
test/react
```
const Link = ({ page, children = <span>hello</span> }: any) => {

// ReferenceError: React is not defined
```
test/failing-test
```
const Fetcher = ({
  children,
  loader = <div>Loading...</div>,
}: {
  children: Function | null;
  loader?: React.ReactNode;
}) => {

// ReferenceError: React is not defined

```

**Comment by antfu** [comment]
I guess it's probably a bug of Vite or esbuild that does not scan the JSX in certain position of AST

**Comment by Aslemammad** [comment]
@fadi-george says it works in vite!

**Comment by Aslemammad** [comment]
@antfu Let's close this if you want!

**Pull request closed without merging**
