### PR TITLE
chore(examples): update react-storybook example to storybook v8

### PR DESCRIPTION
**Pull request by shilman**
### Description

This PR updates `examples/react-storybook` to Storybook v8.

The current example uses v6, and Storybook has progressed a lot since then. With respect to testing, the package `@storybook/testing-react` has been deprecated and the functionality has been moved to `@storybook/react` and dramatically improved.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
Thank you! We do need to go through examples and remove some of them.

**Review by sheremet-va — APPROVED** [review]

**Comment by hi-ogawa** [comment]
`react` v17 and `react-query` v3 (the latest would be `@tanstack/react-query` v5) are probably old for a modern app. If it's not too much change, then it would be great to upgrade them too.

**Comment by shilman** [comment]
Thanks @sheremet-va ! We've done a lot of work to make Storybook stories more compatible with Vitest, and will hopefully have a small documentation PR coming your way soon.

Thanks @hi-ogawa -- good spot, I'll try to upgrade those too.

Will try to get this PR over the line in the next week or so. Thanks for your patience and for building such a wonderful tool! 🙏

**Comment by sheremet-va** [comment]
We removed some duplicate examples including react-storybook.

**Pull request closed without merging**
