### PR TITLE
fix(snapshot): improve inline snapshot inside loop rejection

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Follow up to https://github.com/vitest-dev/vitest/pull/6332#discussion_r1715030916

I had a concern about potential performance impact of doing `parseErrorStacktrace + processStackTrace` for all `toMatchInlineSnapshot`, but I'm hoping it's probably negligible for what happens during the entire life of `toMatchInlineSnapshot` (at least there's no visible difference on our CI).

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by sheremet-va — APPROVED** [review]

**Comment by hi-ogawa** [comment]
This change broke Vue CI https://discord.com/channels/917386801235247114/1277496967060127774/1277499315119587348 Vue has been using `toMatchInlineSnapshot` which is already broken in some scenarios, so I'm not exactly sure what we should do. For now I added it to team board so we can discuss it later.

**Comment by edison1105** [comment]
@hi-ogawa 
This change broke the test case in `vuejs/core`. see https://github.com/vuejs/core/pull/11941/files
This will prevent `core` from upgrading to the latest version of Vitest. Would this be considered a bug, and is there any way to avoid it?

**Comment by hi-ogawa** [comment]
@edison1105 We were aware that this breaks Vue's usage, but after the discussion within the team, we decided this PR is a valid fix. This is because we cannot support creating/updating snapshot for such usage even though the tests were passing as long as  snapshot matches. We suggest replacing `toMatchInlineSnapshot` with `toBe` for your use case.

**Comment by hi-ogawa** [comment]
This PR's title might be confusing, but this PR (also with the last PR https://github.com/vitest-dev/vitest/pull/6332) detects `toMatchInlineSnapshot` being called multiple times at the same location. Simplified example of Vue's pattern is something like this:

```ts
import { describe, test, expect } from "vitest";

function runSharedTests(someFlag) {
  test("shared test", () => {
    expect(1).toMatchInlineSnapshot(`1`) // not allowed
  })
}

describe("true", () => {
  runSharedTests(true);
})

describe("false", () => {
  runSharedTests(false);
})
```

Other than replacing `toMatchInlineSnapshot`, you can also workaround this by splitting `toMatchInlineSnapshot` calls based on the flag:

```ts
function runSharedTests(someFlag) {
  test("shared test", () => {
    if (someFlag) {
      expect(1).toMatchInlineSnapshot(`1`)
    } else {
      expect(1).toMatchInlineSnapshot(`1`)
    }
  })
}
```

**Comment by edison1105** [comment]
@hi-ogawa 
I appreciate your suggestion. We now use `toBe` to replace `toMatchInlineSnapshot` in those tests

**Pull request merged**
