### PR TITLE
fix(env-replacer): don't modify string literals

### LINKED ISSUE #1941: vite:env-replacer incorrectly replaces import.meta.env inside string literals and comments
related [vitejs/vite#9791](https://github.com/vitejs/vite/pull/9791/files/bb34dd12da630df982f9d4c7a371841684f59217#diff-549eafb0508edbd712731e6b064bf7f4ac695383189a619d607bc3167a51611e)

### Describe the bug

The `vite:env-replacer` plugin is indiscriminately replacing `import.meta.env` everywhere in a source file, including string literals and comments.

For example, this test file:

```js
// MyComponent.spec.js
test('ignores import.meta.env', () => {})
```

...gets transformed into:

```js
// MyComponent.spec.js
test('ignores process.env', () => {})
```

Another example:

```js
// importMetaEnv.test.ts
it('import.meta.env equals import' + '.meta.env', () => {
  expect('import.meta.env').toBe('import' + '.meta.env') // ❌ fails
})
```

...which results in:

```shell
 ❯ test/importMetaEnv.test.ts (1)
   ❯ process.env (1)
     × process.env equals import.meta.env

 ❯ eval test/importMetaEnv.test.ts:5:30
      3| describe('import.meta.env', () => {
      4|   it('import.meta.env equals import' + '.meta.env', () => {
      5|     expect('import.meta.env').toBe('import' + '.meta.env');
       |                              ^
      6|   });
      7| });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/importMetaEnv.test.ts > process.env > process.env equals import.meta.env
AssertionError: expected 'process.env' to be 'import.meta.env' // Object.is equality
  - Expected   "import.meta.env"
  + Received   "process.env"

Test Files  1 failed (1)
     Tests  1 failed (1)
  Start at  23:19:24
  Duration  49ms
```

### Workaround

Use string concatenation to avoid the string replacement (as was done in the `importMetaEnv.test.ts` above):

```js
'import' + '.meta.env'
```

### Solution 1: Strip literals from analysis

Use `strip-literal` on the [string being scanned for `import.meta.env`](https://github.com/vitest-dev/vitest/blob/924ba44/packages/vitest/src/node/plugins/envRelacer.ts#L13):

```diff
-const envs = code.matchAll(/\bimport\.meta\.env\b/g)
+if (!/\bimport\.meta\.env\b/g.test(code))
+  return null
+
+const envs = stripLiteral(code).matchAll(/\bimport\.meta\.env\b/g)
```

This would mimic [the way Vite does it](https://github.com/vitejs/vite/pull/8054).

### Solution 2: Remove `EnvReplacer`; use Vite `env` instead

Vite already replaces `import.meta.env` in its [`vite:define` plugin](https://github.com/vitejs/vite/blob/7d810a9/packages/vite/src/node/plugins/define.ts#L48-L55) and [`vite:import-analysis` plugin](https://github.com/vitejs/vite/blob/7d810a9e157b232c44490bee8016a08bc9167c50/packages/vite/src/node/plugins/importAnalysis.ts#L580-L593), so this plugin seems unnecessary.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-jw9wba?file=test%2FimportMetaEnv.test.ts&initialPath=__vitest__)

### System Info

```shell
System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 259.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 8.15.0 - ~/n/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5271.0
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    vite: ^3.0.9 => 3.0.9 
    vitest: workspace:* => 0.22.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by tony19**
fix #1941

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Can you add a test case for this?

**Comment by tony19** [comment]
Sure. I don't see any plugin specific tests in `tests/`. Where should I test this?

**Comment by antfu** [comment]
You can add a new test that contains `import.meta.env` as an string and do assertions to ensure it's not been replaced

**Comment by sheremet-va** [comment]
> Sure. I don't see any plugin-specific tests in `tests/`. Where should I test this?

I think we have `env.test.ts`

**Comment by tony19** [comment]
The [`test-ui` job crashed when starting Cypress](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true):

```
Run pnpm run ui:test

> @vitest/monorepo@0.22.1 ui:test /home/runner/work/vitest/vitest
> npm -C packages/ui run test:run


> @vitest/ui@0.22.1 test:run
> cypress run --component

It looks like this is your first time using Cypress: 10.6.0

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...
[22[7](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:8)4:0[8](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:9)31/061601.600053:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
(node:2285) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2285) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/runner/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/ts-node/esm/transpile-only.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:[9](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:10)1:5)
    at async handleMainPromise (node:internal/modules/run_main:65:[12](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:13)) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}
Error: The operation was canceled.
```

That doesn't seem related to my changes, and I can't reproduce it locally.

**Comment by tony19** [comment]
The `test-ui` job is failing when starting Cypress:

```none
Run pnpm run ui:test

> @vitest/monorepo@0.22.1 ui:test /home/runner/work/vitest/vitest
> npm -C packages/ui run test:run


> @vitest/ui@0.22.1 test:run
> cypress run --component

It looks like this is your first time using Cypress: 10.6.0

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...
[22[7](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:8)4:0[8](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:9)31/061601.600053:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
(node:2285) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2285) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/runner/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/ts-node/esm/transpile-only.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:[9](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:10)1:5)
    at async handleMainPromise (node:internal/modules/run_main:65:[12](https://github.com/vitest-dev/vitest/runs/8107375777?check_suite_focus=true#step:6:13)) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}
Error: The operation was canceled.
```

This is unrelated to my changes because I can reproduce it locally on the `main` branch.

**Comment by antfu** [comment]
You can ignore the Cypress error for now

**Review by antfu — APPROVED** [review]

**Comment by tony19** [comment]
The [test failure](https://github.com/vitest-dev/vitest/runs/8125620131?check_suite_focus=true) is unrelated to my changes, as it's also happening on the `main` branch. Not yet sure what the cause is.

**Pull request merged**
