### PR TITLE
fix(utils): Ensure test.each print -0 and -NaN properly

### PR DESCRIPTION
**Pull request by pengooseDev**
### Description
Fixes [issue #5744](https://github.com/vitest-dev/vitest/issues/5744)

This bug fix ensures that when using test.each, the descriptive text for `-0` and `-NaN` is correctly printed as `-0` and `-NaN` instead of `0` and `NaN`.

For better readability, I have standardized the test conventions to `it should be formatted ...` for added tests. Additionally, I plan to create an issue soon to discuss improving test code readability and establishing conventions. I welcome any feedback on the code and the proposed direction. :)

- enhance format logic
- add test suite(formats special cases)
- add util function(isNegativeNaN)
- add test suite(isNegativeNaN)

image
+ I have ensured that the descriptive text for -0 and -NaN is printed correctly as -0 and -NaN instead of 0 and NaN when using test.each. The issue was not with the each method itself, and the tests have passed successfully.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
It doesn't look like this is how Node.js does it:

https://nodejs.org/api/util.html#utilformatformat-args

> %f: parseFloat(value) is used for all values expect Symbol.

**Comment by pengooseDev** [comment]
@sheremet-va 
Thanks for yout feedback. :)

Issue #5744 requests that `-0` and `-NaN` should be rendered as `-0` and `-NaN` respectively when formatted with %f, instead of 0 and NaN. Considering the `pending triage` label has been removed and the `p2-edge-case` label has been added, I understood this as an indication of support for this feature.

1. I am curious if you would like to add the functionality to format -0 and -NaN as they are with the %f format. If it is determined to be difficult to implement, I will close this PR and work on other tasks. :)

2. If you would like to add this feature, I would appreciate your feedback on how the code should be changed to achieve this (e.g., changing the location of the logic).

### Why ArrayBuffer?
+ parseFloat returns 0 and NaN for -0 and -NaN respectively. Additionally, Object.is(NaN, -NaN) and Object.is(NaN, NaN) both return false, making it difficult to check the sign of NaN without the help of ArrayBuffer. This is why I added the isNegativeNaN function.

+ If you believe this approach does not align with your desired direction, please feel free to close this PR. I am always greatly helped by the amazing Vitest project. Thank you. :)

**Comment by sheremet-va** [comment]
> Issue #5744 requests that `-0` and `-NaN` should be rendered as `-0` and `-NaN` respectively when formatted with %f, instead of 0 and NaN. Considering the `pending triage` label has been removed and the `p2-edge-case` label has been added, I understood this as an indication of support for this feature.

Yes, I am fine with changing this in `.each`, but it doesn't mean we can change the Node.js `format` since it would be a breaking change. I will be happy if we can bypass this somehow.

> Why ArrayBuffer?

I am fine with any implementation of `-NaN` detection.

**Comment by pengooseDev** [comment]
I understand :) First of all, after revert the changes, I will also try to find a way with you.
If you find a good way, I would appreciate it if you could comfortably leave a comment on the PR.
Thank you for your direction!

**Comment by pengooseDev** [comment]
I'll create new PR soon :)

**Pull request closed without merging**
