### PR TITLE
chore: add defaults to exports

### PR DESCRIPTION
**Pull request by goosewobbler**
### Description

Most of the packages use conditional exports without a `default` or `require` value so are not able to be used in CJS projects.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
None required

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
This is intentional. They cannot be used in CJS project even with this because we don't bundle CJS.

**Comment by goosewobbler** [comment]
Well, we're trying to use `@vitest/spy` and our CJS E2Es aren't working, rollup can't resolve that dependency.  Simply adding a default export fixes them.  Why are there default exports in some of the packages but not others?

**Comment by sheremet-va** [comment]
> rollup can't resolve that dependency

It cannot resolve it because it follows Node.js resolution, and fails correctly. Vitest and its dependencies cannot be imported using `require` which rollup assumes will be the output.

**Comment by sheremet-va** [comment]
On the other hand, it gives different errors:

Screenshot 2023-11-10 at 13 43 53
Screenshot 2023-11-10 at 13 43 59

The last one (that you currently get) is kind of cryptic, so it might be better to add this `default` condition.

**Review by sheremet-va — CHANGES_REQUESTED** [review]
I think we can merge this PR if `"import"` is just replaced with `"default"` (not added as an additional one) - even though `import` is the correct export, `default` gives a more meaningful error message

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
