### PR TITLE
chore: fix local dev missing dep

### PR DESCRIPTION
**Pull request by posva**
### Description

I noticed the package wasn't installed to run the project. If that's intentional, ignore the PR or feel free to just add manually and close this

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
Ah, that's where it was used. Can't we just use `&`?

> "dev:ui": "pnpm run dev & pnpm run dev:client"

**Comment by sheremet-va** [comment]
> The main advantage is that this version works on Windows (I think). See [mysticatea/npm-run-all@`master`/docs/run-p.md](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md?rgh-link-date=2024-02-09T16%3A01%3A22Z)

We use pnpm's `shell-emulator`, I wonder if it will just work 🤔

**Comment by hi-ogawa** [comment]
Thanks for the PR. I also noticed that and just wanted to confirm with others.

There are two `run-p` and I'm currently hitting the first one which fails when running `pnpm dev` from root:

```sh
$ pnpm dev
...
packages/browser dev: command not found: run-p
packages/browser dev: Failed
/home/hiroshi/code/others/vitest/packages/browser:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vitest/browser@1.2.2 dev: `rimraf dist && run-p dev:node dev:client`
Exit status 127
 ELIFECYCLE  Command failed with exit code 1.
```

https://github.com/vitest-dev/vitest/blob/5ed537f03ea33df3516e530b55a5c1f0fc219e24/packages/browser/package.json#L47-L49

https://github.com/vitest-dev/vitest/blob/c441a7533a97ddff3737dcaa893199374895422b/packages/ui/package.json#L41-L43

How about using `pnpm run` with regex?

```diff
diff --git a/packages/browser/package.json b/packages/browser/package.json
index efeba6c3..8f1c4b4c 100644
--- a/packages/browser/package.json
+++ b/packages/browser/package.json
@@ -49 +49 @@
-    "dev": "rimraf dist && run-p dev:node dev:client",
+    "dev": "rimraf dist && pnpm run --stream '/^dev:/'",
diff --git a/packages/ui/package.json b/packages/ui/package.json
index b7189664..70412026 100644
--- a/packages/ui/package.json
+++ b/packages/ui/package.json
@@ -43 +43 @@
-    "dev:ui": "run-p dev dev:client",
+    "dev:ui": "pnpm run --stream '/^(dev|dev:client)$/'",
```

**Comment by sheremet-va** [comment]
We merged pnpm --stream instead

**Comment by posva** [comment]
Nice, I didn't know about this pnpm feature

**Pull request closed without merging**
