### PR TITLE
chore(docs): update team page

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

I just noticed that I was already in team emeriti side..

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by hi-ogawa** [comment]
It looks like chrome webdriverio is down now

- https://github.com/webdriverio/webdriverio/issues/12251

I'm not sure if there is any quick env var workaround this time.

**Comment by christian-bromann** [comment]
@hi-ogawa there is a temporary workaround which is setting `browserVersion: "122.0.6261.39"` in the capabilities. Unfortunately we are still waiting for the Chrome team to release a patch.

**Comment by hi-ogawa** [comment]
@christian-bromann Thanks for the info!

Right, it looks like it can workaround from Vitest config `providerOptions`, so I guess it's not an absolute blocker for Vitest users. I tested this locally on `examples/lit`:

https://github.com/vitest-dev/vitest/blob/7d9b1fb02338beef048487ef07f6083aa5559106/examples/lit/vite.config.ts#L10

```tsx
export default defineConfig({
  test: {
    browser: {
      enabled: true,
      name: 'chrome',
      providerOptions: {
        capabilities: {
          browserVersion: "122.0.6261.39"
        }
      }
    },
  },
})
```

For Vitest's tests itself, there are a few places using webdriverio + chrome, so putting this workaround might a bit tedious, so I think we'll wait a bit to see how chrome and puppeteer side goes.

**Review by AriPerkkio — APPROVED** [review]

**Review by sheremet-va — APPROVED** [review]

**Comment by christian-bromann** [comment]
> so I think we'll wait a bit to see how chrome and puppeteer side goes.

We have a fix in the works and release later today.

**Pull request merged**
