### PR TITLE
fix: use ws 8.4.0 to try to fix SB

### PR DESCRIPTION
**Pull request by patak-dev**

### CODE REVIEW

**Comment by antfu** [comment]
What's the root cause of this? 👀

**Comment by userquin** [comment]
> What's the root cause of this? 👀

https://imgur.com/DxkZUjI

**Comment by userquin** [comment]
Basic test ui on Stackblitz not working, we have test also with ws 8.4.2 but it seems some change on ws breve the web socket

**Comment by userquin** [comment]
Check also discord help room conversation

**Comment by patak-dev** [comment]
@antfu I'll talk with @d3lm on Monday. Looks like ws 8.4.1 surfaced a bug in StackBlitz, locally it works fine. Our CI looked more unreliable, so maybe it is a race condition that hits harder in SB. There was a patch for ws (8.4.2) that we tried without success, maybe we just need to wait a few patches

**Comment by d3lm** [comment]
This is a bug in WebContainer and we try to prioritize this and fix it asap.

**Pull request merged**
