### PR TITLE
feat: ensure mocking plugin is the last one

### PR DESCRIPTION
**Pull request by sheremet-va**

### CODE REVIEW

**Review by antfu — APPROVED** [review]
Pushed a change, and verified it fixing `nuxt-vitest`'s failing

**Comment by sheremet-va** [comment]
> Pushed a change, and verified it fixing `nuxt-vitest`'s failing

It should run after vite-analyzer.

**Comment by sheremet-va** [comment]
@antfu do you want to look into this?

**Comment by sheremet-va** [comment]
@antfu I am not sure about your change. What if another package will also use `order: 'post'`? Isn't it safer to modify plugins?

Currently, it doesn't work because Vite already resolved `vitest` entry and changed all imports. Mocks plugin expects that it didn't happen yet.

**Comment by huang-julien** [comment]
Hi :wave: is there some kind of workaround for this issue ? This is quite blocking for nuxt-vitest

**Comment by sheremet-va** [comment]
> Hi 👋 is there some kind of workaround for this issue ? This is quite blocking for nuxt-vitest

From my point of view, @antfu overtook this PR. So I am personally waiting on his actions/comments 😄

**Comment by oskarols** [comment]
@antfu Anything we can do to help this move forward? 🙏

**Pull request closed without merging**
