### PR TITLE
fix: correctly resolve filename, when running code

### LINKED ISSUE #2425: Relative paths in `test.alias` cause uncovered files in `c8` reports
### Describe the bug

There has been couple of reports that `c8` coverage reports can be missing files. I finally received a reproduction repository and was able to debug this issue.

If user configures `test.alias` using relative paths, the coverage report from `c8` can be missing files that are imported using the aliased path. Using absolute paths in `test.alias` **works always**. Does this look like a bug in `rollup-plugin-alias`  or something that could be handled on Vitest's or Vite's side?

#### Relative path

```
├── src // This is aliased as @some-alias
|  ├── animals.test.ts // imports '@some-alias/animals'
|  ├── animals.ts
|  └── math.ts
├── test
|  └── nested
|     └── math.test.ts // imports '@some-alias/math'
└── vite.config.ts
```

```js
export default defineConfig({
  test: {
    alias: {
      "@some-alias": "./src"
...
```

Tests run OK. Coverage report is empty.

```
% Coverage report from c8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
```

The `rollup-plugin-alias` used by Vite is here returning `{ id: './src/math' }` for `resolveId('@some-alias/math')`.

The final transformed test case contains following import:
```
const __vite_ssr_import_1__ = await __vite_ssr_import__("/@id/src/math");
```

The V8 coverage reports contain paths which are not File URLs. `c8` does not pick these up.
```js
{
  "scriptId": "761",
  "url": "src/math", // <-- Should be File URL with absolute path + extension
  "functions": [...]
```

#### Absolute path

```js
import path from "path";

export default defineConfig({
  test: {
    alias: {
      "@some-alias": path.resolve("./src")
...
```

Coverage report is complete.

```
% Coverage report from c8
------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------|---------|----------|---------|---------|-------------------
All files   |   68.18 |    57.14 |     100 |   68.18 |
 animals.ts |   72.72 |       50 |     100 |   72.72 | 3-5
 math.ts    |   63.63 |    66.66 |     100 |   63.63 | 7-10
------------|---------|----------|---------|---------|-------------------
```

Here `rollup-plugin-alias` is returning full path, **including extension**, `{ id: '/Users/x/y/vitest-c8-test-alias/src/math.ts' }` for `resolveId('@some-alias/math')`.

The final transformed test case contains following import:
```
const __vite_ssr_import_1__ = await __vite_ssr_import__("/src/math.ts");
```

The V8 coverage reports contain File URLs now. `c8`  can process these successfully:
```js
{
  "scriptId": "761",
  "url": "file:///Users/x/y/vitest-c8-test-alias/src/math.ts",
  "functions": [...]
  ...
```

### Reproduction

Make sure you download this as `c8` does not work on Stackblitz: https://stackblitz.com/edit/vitest-dev-vitest-n4nrrs

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 677.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 107.1.45.133
    Safari: 15.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #2425

### CODE REVIEW

**Review by AriPerkkio — APPROVED** [review]
URLs in V8 coverage reports seem correct and coverage report includes expected files:

```json
{
    "scriptId": "763",
    "url": "file:///Users/x/y/vitest-c8-test-alias/src/math.ts",
    "functions": [...]
}
```

```
% Coverage report from c8
------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------|---------|----------|---------|---------|-------------------
All files   |     100 |      100 |     100 |     100 |                   
 animals.ts |     100 |      100 |     100 |     100 |                   
 math.ts    |     100 |      100 |     100 |     100 |                   
------------|---------|----------|---------|---------|-------------------
```

**Review by AriPerkkio — CHANGES_REQUESTED** [review]
Hold on, actually it looks like the coverage report is now incorrect. It states files are covered 100% even though tests are not testing everything.

```
alias: { "@some-alias": "./src" }

 % Coverage report from c8
------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------|---------|----------|---------|---------|-------------------
All files   |     100 |      100 |     100 |     100 |                   
 animals.ts |     100 |      100 |     100 |     100 |                   
 math.ts    |     100 |      100 |     100 |     100 |                   
------------|---------|----------|---------|---------|-------------------
```

```
alias: { "@some-alias": resolve("./src") }

 % Coverage report from c8
------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------|---------|----------|---------|---------|-------------------
All files   |   68.18 |    57.14 |     100 |   68.18 |                   
 animals.ts |   72.72 |       50 |     100 |   72.72 | 3-5               
 math.ts    |   63.63 |    66.66 |     100 |   63.63 | 7-10              
------------|---------|----------|---------|---------|-------------------
```

**Comment by sheremet-va** [comment]
@AriPerkkio should be fixed now. C8 coverage provider used previous ID instead of correct file path.

**Comment by AriPerkkio** [comment]
Coverage report is now locally correct. However the tests on CI seem to be stuck.

**Review by AriPerkkio — APPROVED** [review]

**Pull request merged**
