### PR TITLE
fix: throw an error and a warning if `.poll`, `.element`, `.rejects`/`.resolves`, and `locator.*` weren't awaited

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

If `expect.poll().to*` or `expect.element().to*` is not awaited, the test will now fail. The stack trace leads to the line where it's called. The callback to `.poll` will never be called to avoid unhandled rejections.

Screenshot 2024-11-07 at 15 20 44

If `expect.rejects`/`expect.resolves` was not awaited, Vitest will print a warning:

Screenshot 2024-11-08 at 14 31 48

If async `locator.*` methods are not awaited, Vitest will fail the test. The RPC will never be called to avoid unhandled rejections:

Screenshot 2024-11-08 at 14 34 01

TODO:
- [x] Test
- [x] Docs update

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
@hi-ogawa this was pretty easy to do 😄

**Comment by Smrtnyk** [comment]
I was bitten by this many times :sweat:  
good stuff to have this

**Review by hi-ogawa — APPROVED** [review]
Looks good to me :+1: 
One caveat is that it's not a genuine promise tracker, so something like these get through.

```ts
test('repro', async () => {
  myPollWrapper();

  Promise.all([
    expect.poll(() => 3).toBe(4),
    expect.poll(() => 3).toBe(4),
  ]);
})

async function myPollWrapper() {
  await expect.poll(() => 3).toBe(4);
}
```

But these are only false-negative of some edge cases and I don't see any false-positive, so this should be a nice improvement.

**Review by AriPerkkio — DISMISSED** [review]
Looks good! Showing the erroneous line is really nice dx improvement. 💯 

> should we do the same with `.resolves` and `.rejects`?

Sure why not. I'm not familiar with internals of `expect`, but could this be done on any higher level instead of patching all matchers?

**Comment by hi-ogawa** [comment]
> should we do the same with `.resolves` and `.rejects`? 🤔

Does this means we remove `recordAsyncExpect` trick for auto await? I would prefer the change as it would be more well-defined behaviors for users. I guess technically that would be breaking change though.

**Comment by sheremet-va** [comment]
> > should we do the same with `.resolves` and `.rejects`? 🤔
> 
> Does this means we remove `recordAsyncExpect` trick for auto await? I would prefer the change as it would be more well-defined behaviors for users. I guess technically that would be breaking change though.

Hm, I am not sure what is better 🤔 I like to be stricter, but I don't know if we can enforce it now 🤔 The `expect.resolves` basically implicitly becomes `expect.soft.resolves` right now, and it's documented

**Comment by sheremet-va** [comment]
I think maybe we should also throw an error or show a warning if locator methods were not awaited: 

```ts
getByRole('button').click()
expect(button).toHaveText('123')
```

React shows a warning if `React.act` wasn't called, and we can maybe do the same instead of failing the test 🤔

**Pull request merged**
