### PR TITLE
fix(cli): improve colors used when erroring

### PR DESCRIPTION
**Pull request by ghiscoding**
- partially fixes issue #3266 (following this maintainer [comment](https://github.com/vitest-dev/vitest/issues/3266#issuecomment-1539326843))
- previously spec filename link were shown in yellow, I changed the color to cyan making easier to find (same as Jest)
- also remove yellow color from test code highlight, simply reverting to default text color

I find this change to be easier to read, especially in dark mode, the link color that is much quicker to find compare to before since everything used to be yellow.

See before/after below (left/right), the biggest difference is obviously in dark mode because of the contrast

image

image

### CODE REVIEW

**Comment by ghiscoding** [comment]
I'm not sure why the Lint fails, I ran `pnpm run lint:fix` and see no git changes, feel free to recreate the PR if need be, it's only 2 line of code change

**Comment by sheremet-va** [comment]
Do you want to change the placing of the diff to make it easier to spot?

**Comment by ghiscoding** [comment]
@sheremet-va do you mean to move the Expected/Received count before the test code block but after the spec filename (in cyan)? However my demo is a really small unit test, in some cases the user might need to scroll up to see that info, is that still how you want to order these results?

**Comment by sheremet-va** [comment]
> do you mean to move the Expected/Received count before the test code block but after the spec filename (in cyan)?

No, cyan is part of the callstack. The code block is there because it point to a file in source code (the error can be outside of the test file)

I was thinking about moving the diff before the cyan part

**Comment by ghiscoding** [comment]
@sheremet-va I'm not really sure where to change that in the code, I couldn't find in the code where this output is being built.

**Comment by sheremet-va** [comment]
> @sheremet-va I'm not really sure where to change that in the code, I couldn't find in the code where this output is being built.

https://github.com/vitest-dev/vitest/blob/4a807df37bc5da735048040a94b820f06841bfac/packages/vitest/src/node/error.ts#L99

**Comment by ghiscoding** [comment]
@sheremet-va the code you mention just points to a console error, I have a hard time understanding how to do the change you asked, would it be possible to merge the PR without this change? I was more interested in the color change myself, the location of the expected/received doesn't bother me

https://github.com/vitest-dev/vitest/blob/4a807df37bc5da735048040a94b820f06841bfac/packages/vitest/src/node/error.ts#L187-L189

**Pull request merged**
