### PR TITLE
chore: repro --no-threads issues

### PR DESCRIPTION
**Pull request by cexbrayat**
Adds an additional step to the CI job to reproduce the --no-threads issues

### CODE REVIEW

**Comment by antfu** [comment]
Can you share more context about this? Not all tests are capable of running in the same thread.

**Comment by cexbrayat** [comment]
There are currently several issues when running tests with `--no-threads`:

- jsdom issues: it turns out that the teardown function of the jdsom env is never called in threaded mode. When threads are disabled, then the teardown function is called, and tests break
- some mocks and spies tests are failing as well, maybe for a similar reason (`pnpm test -- --no-threads`)

**Comment by cexbrayat** [comment]
@antfu Just saw your comment. There is at least one issue with jsdom (and happy-dom probably) env: their teardown function is never called when threads are enabled if I'm not mistaken. That leads to behavior difference between threaded and non-threaded mode.

**Comment by cexbrayat** [comment]
Related issue #835

**Pull request merged**
