### PR TITLE
test: graphql mock example

### PR DESCRIPTION
**Pull request by Sajad-Sharhani**

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
Could we have a seperate example? Thanks

**Comment by Sajad-Sharhani** [comment]
My previous PR was separate example but @mitchelvanbever said we should put rest and graphql msw example together because their isn't much difference. In which, I agree too.

**Comment by Sajad-Sharhani** [comment]
> Could we have a separate example? Thanks
If you agree, maybe putting more comments will make it clearer if not, I will make a separate example.

**Comment by antfu** [comment]
Ok, let's have it. I don't mind it on either side.

**Pull request merged**
