### PR TITLE
fix: revert concordance diff, use jest's diff output

### LINKED ISSUE #3261: test result diff output containing recursive data never completes
### Describe the bug

We currently setup vitest to test our react components with @resting-lib/react. During the setup we made some mistakes that lead to never completing test runs. After some deep debugging and comparison to jest we discovered that the diff output of some (not so deep) JSX trees contain recursive data structures which cause the test run not to complete. Choosing another reporter, like 'junit' solves the issue completely.

There had been a implementation to limit the diff output, that got lost at a huge change
https://github.com/vitest-dev/vitest/commit/0f86ff98975a80191d6215b0d30ff6cd9f8388d3#diff-1e7604160ec072ba6c4059a1b3c588946c3765ce2944002ef1ece1e438014410L8

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-kkdcxs?file=package.json

This setup uses `"vitest": "latest"` and reproduces the issue. Downgrading `vitest` to `0.29.8` resolves the issue.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.69 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 15.6
  npmPackages:
    @vitest/ui: latest => 0.30.1
    vite: latest => 4.3.2
    vitest: latest => 0.30.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #3553: Diff difference of array of string is difficult to read
### Describe the bug

Using: vitest/0.32.0 darwin-arm64 node-v20.2.0

When trying toStrictEqual an array of string, if one line is missing the result if very difficult to read.

Result using vitest

image

The result using jest is 

image

### Reproduction

test('simpleCase', () => {
  expect([
    'dataUnzip/data.zip/data/c.txt - c.txt',
    'dataUnzip/data.zip/data/d.txt - d.txt',
    'dataUnzip/data.zip/data/dir1/a.txt - a.txt',
    'dataUnzip/data.zip/data/dir1/b.txt - b.txt',
    'dataUnzip/data.zip/data/dir1/dir3/e.txt - e.txt',
    'dataUnzip/data.zip/data/dir1/dir3/zipFile3.zip/c.txt - c.txt',
    'dataUnzip/data.zip/data/dir1/dir3/zipFile3.zip/d.txt - d.txt',
    'dataUnzip/dir1/a.txt - a.txt',
    'dataUnzip/dir1/b.txt - b.txt',
    'dataUnzip/dir1/dir3/e.txt - e.txt',
    'dataUnzip/dir1/dir3/f.txt - f.txt',
    'dataUnzip/dir2/c.txt - c.txt',
    'dataUnzip/dir2/d.txt - d.txt',
    'dataUnzip/dir2/data.zipped - data.zipped',
  ]).toStrictEqual([
    'dataUnzip/data.zip/data/c.txt - c.txt',
    'dataUnzip/data.zip/data/d.txt - d.txt',
    'dataUnzip/data.zip/data/dir1/a.txt - a.txt',
    'dataUnzip/data.zip/data/dir1/b.txt - b.txt',
    'dataUnzip/data.zip/data/dir1/dir3/e.txt - e.txt',
    'dataUnzip/data.zip/data/dir1/dir3/f.txt - f.txt',
    'dataUnzip/data.zip/data/dir1/dir3/zipFile3.zip/c.txt - c.txt',
    'dataUnzip/data.zip/data/dir1/dir3/zipFile3.zip/d.txt - d.txt',
    'dataUnzip/dir1/a.txt - a.txt',
    'dataUnzip/dir1/b.txt - b.txt',
    'dataUnzip/dir1/dir3/e.txt - e.txt',
    'dataUnzip/dir1/dir3/f.txt - f.txt',
    'dataUnzip/dir2/c.txt - c.txt',
    'dataUnzip/dir2/d.txt - d.txt',
    'dataUnzip/dir2/data.zipped - data.zipped',
  ]);
});

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 65.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.volta/tools/image/node/20.2.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.6 - ~/.volta/tools/image/node/20.2.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Chrome Canary: 116.0.5818.0
    Firefox: 113.0.1
    Safari: 16.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #3560: After switch to concordance, diff on large objects sometimes does not show
### Describe the bug

The following test fails as expected, but doesn't print the diff between `actual` & `expected`: https://gist.github.com/ldiqual/f874381a2e836fc57ca8c07be9f2f397
I believe this is due to https://github.com/vitest-dev/vitest/blob/main/packages/utils/src/diff.ts#L27-L28 which expects a specific color from the concordance output. However it sounds like concordance sometimes prints a 31m red plus, instead of a 32m green plus.

After inserting a bunch of console logs in @vitest/utils/diff.js, this is the raw output from concordance and the plus/minus that vitest expects:

```
Line:
"  +   contractSumToDatePreTax: 90909"

Raw:
"  \u001b[31m+\u001b[39m   contractSumToDatePreTax: \u001b[33m90909\u001b[39m\u001b[90m,\u001b[39m"

Plus:
"  \u001b[32m-\u001b[39m "

Minus:
"  \u001b[32m+\u001b[39m"
```

### Reproduction

Run the following test: https://gist.github.com/ldiqual/f874381a2e836fc57ca8c07be9f2f397

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 111.31 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/27761_1686604561032/bin/node
    Yarn: 3.6.0 - ~/Library/Caches/fnm_multishells/27761_1686604561032/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/27761_1686604561032/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 109.0
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-react-swc: 3.3.2 => 3.3.2
    vite: 4.3.9 => 4.3.9
    vitest: 0.32.0 => 0.32.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
This PR reimplements Jest's diffing algorithm and the way it's outputted for our use case (better browser support, don't use chalk). It seems like concordance was not a good choice _right now_, but we can reevaluate it in the future. The main feature we are now lacking is showing string difference (now it's just +/-), but we can improve it later ourselves without relying on another library:

Closes #3261
Closes #3560
Closes #3553

### CODE REVIEW

**Review by antfu — APPROVED** [review]
I am ok with that. And at some point, maybe we will have an in-house solution? 👀

**Comment by nstepien** [comment]
Looks like the dependency on concordance is still there, not sure if this is intentional or not.
https://github.com/search?q=repo%3Avitest-dev%2Fvitest%20concordance&type=code

**Comment by sheremet-va** [comment]
> Looks like the dependency on concordance is still there, not sure if this is intentional or not. https://github.com/search?q=repo%3Avitest-dev%2Fvitest%20concordance&type=code

It wasn't even intentional before 🤔 Thank you for noticing, I will create a separate PR

**Comment by wycats** [comment]
It looks like this change may have caused the output in `@vitest/ui` to print ANSI escape codes.

image

I'm not sure what the root cause is, but I'm sure it started after I upgraded vitest this week.

**Pull request merged**
