### PR TITLE
ci: run tests sequentially 

### PR DESCRIPTION
**Pull request by sheremet-va**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
> Is #5678 on this branch?

Yes, these failings are why I opened a PR. No idea why it's failing yet.

**Comment by sheremet-va** [comment]
> is failing randomly without any error logs

Do you think it might be because we have 3 different pools that have their own min/max worker count?

**Comment by AriPerkkio** [comment]
Oh right, those pools are run in parallel. The failing linux CIs have 2 CPUs so each pool is using just one worker. But still there's main thread + 3 pool threads running.

**Comment by AriPerkkio** [comment]
Actually I can reproduce this issue locally with Node `v22.1.0` - really weird:


https://github.com/vitest-dev/vitest/assets/14806298/6fe62d9f-1252-413a-b40a-a950bacc9408

**Comment by AriPerkkio** [comment]
Isolated the crashing test to `pnpm run test --run --project=vmThreads injector-mock.test.ts`. Changing that file to contain just the content below is enough to crash:

```ts
import { test } from 'vitest'
import { hoistMocks } from '../../../packages/vitest/src/node/hoistMocks'

test.only('Helloo', () => {
  console.log(hoistMocks)
})
```

**Comment by sheremet-va** [comment]
> Isolated the crashing test to `pnpm run test --run --project=vmThreads injector-mock.test.ts`. Changing that file to contain just the content below is enough to crash:
> 
> ```ts
> import { test } from 'vitest'
> import { hoistMocks } from '../../../packages/vitest/src/node/hoistMocks'
> 
> test.only('Helloo', () => {
>   console.log(hoistMocks)
> })
> ```

Interesting. The only thing I can think of is that it imports parseAst which relies on a native swc module 🤔

**Comment by sheremet-va** [comment]
> The only thing I can think of is that it imports parseAst

Oh, it doesn't actually import it, the plugin provides it 🤔

**Comment by sheremet-va** [comment]
Looks like importing `generateCodeFrame` can cause this. Digging deeper 🔍

**Comment by sheremet-va** [comment]
Almost always fails when importing `vite`:

```
creating module : /vitest/node_modules/.pnpm/vite@5.2.6_@types+node@20.11.5/node_modules/vite/dist/node/index.js
```

🔍 

https://github.com/vitest-dev/vitest/blob/0227e8cbb4db2498d50cf0cc20dc12711e8374ae/packages/vitest/src/runtime/external-executor.ts#L232

**Comment by sheremet-va** [comment]
Looks like it always fails here:

https://github.com/vitest-dev/vitest/blob/0227e8cbb4db2498d50cf0cc20dc12711e8374ae/packages/vitest/src/runtime/vm/file-map.ts#L11

No error, just exit with 129 code - interestingly, it kills even the main thread

**Review by AriPerkkio — COMMENTED** [review]
Could you try if `v22.0.0` works on CI? Locally it doesn't crash like `v22.1.0` does. This could help to pinpoint the root cause. 👀 

https://github.com/vitest-dev/vitest/blob/bcccce6df63b7c0408c6d14978e7cde82f1c90ca/.github/workflows/ci.yml#L42

```diff
-        node_version: [18, 20, 22]
+        node_version: [18, 20, 22.0.0]
```

**Comment by sheremet-va** [comment]
> Could you try if `v22.0.0` works on CI? Locally it doesn't crash like `v22.1.0` does. This could help to pinpoint the root cause. 👀
> 
> https://github.com/vitest-dev/vitest/blob/bcccce6df63b7c0408c6d14978e7cde82f1c90ca/.github/workflows/ci.yml#L42
> 
> ```diff
> -        node_version: [18, 20, 22]
> +        node_version: [18, 20, 22.0.0]
> ```

Actually, I am not even sure why we test against Node 22, it's not LTS yet. We usually wait for it to be LTS or close to it before we add it to CI because it's prone to bugs like this,

**Comment by AriPerkkio** [comment]
Sure, we could drop it until its LTS plans have been announced and add it back some weeks/months before that.

**Pull request merged**
