### PR TITLE
fix: overwrite global URL with environment's

### LINKED ISSUE #3984: v0.34.0 "URL is not defined" failure when using `isolate: false`
### Describe the bug

After upgrading from `vitest` version 0.33.0 to 0.34.0 I'm seeing this failure in any tests which rely on the `URL` global:

```
ReferenceError: URL is not defined
```

I'm guessing this is related to the change in:
- #3828

What's interesting is that my failure only occurs when `isolate: false` is used. Setting `isolate: true` makes the problem go away. The error also doesn't happen when focusing on specific tests in watch mode. It only shows up when running my entire test suite.

Rolling back to 0.33.0 fixes the issue.

### Reproduction

I haven't been able to reproduce via StackBlitz in a minimal scenario yet, so it's possible it's caused by some interplay between other tests, or perhaps the order in which tests run?

Any advice on what the issue might be? Maybe I can give it another try.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 79.16 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Chrome Canary: 118.0.5956.0
    Edge: 114.0.1823.55
    Firefox: 116.0.2
    Safari: 16.5.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #3985: TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob
### Describe the bug

Starting with 0.34, tests are failing with `TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob`. While I can add node Blob in global setup like in https://github.com/vitest-dev/vitest/issues/1377#issuecomment-1141411249 , this creates inconsistent behaviors for the test vs. web based execution.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-aubhih?file=package.json,main.jsx,main.test.jsx,vite.config.js&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 5.47 GB / 7.45 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.2 - ~/node_modules/.bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.0.1 => 1.0.1
    @vitejs/plugin-react-swc: ^3.3.2 => 3.3.2
    @vitest/coverage-v8: 0.33.0 => 0.33.0
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.2 => 0.34.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #3985
Fixes #3984

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by pongells** [comment]
@sheremet-va if I update to 0.34.6 which has this fix, my tests break. I am using Yarn3 with PNP and Node 18.17.1 in a React project.

```
Error: The "path" argument must be of type string or an instance of URL. Received an instance of URL
Require stack:
- /Users/blabla/Workspace/apps/blabla/.yarn/cache/react-npm-18.2.0-1eae08fee2-88e38092da.zip/node_modules/react/cjs/react-jsx-dev-runtime.development.js
```

**Comment by Mrazator** [comment]
Hi @sheremet-va! Is it possible that this changed re-introduced the following issue #3826? We can still reproduce this with vitest 1.5.3 and node 18.X. On node 20.X the problem disappears.

https://github.com/excalidraw/excalidraw/actions/runs/9543859364/job/26302424907#step:4:1826

**Comment by sheremet-va** [comment]
> Hi @sheremet-va! Is it possible that this change re-introduced the following issue #3826? We can still reproduce the issue with vitest 1.5.3 and node 18.X. On node 20.X the problem disappears.
> 
> [excalidraw/excalidraw/actions/runs/9543859364/job/26302424907#step:4:1826](https://github.com/excalidraw/excalidraw/actions/runs/9543859364/job/26302424907#step:4:1826)

This is expected error: https://github.com/vitest-dev/vitest/issues/4043

Since there is no universal solution, we ended up on this one. If you need the Node.js URL, you can overwrite it in `setupFiles`:

```ts
import { URL } from 'node:url'
globalThis.URL = URL
```

**Comment by Mrazator** [comment]
Alright, thank you!

**Pull request merged**
