### PR TITLE
fix(vite-node): don't remove sourcemap string in source code (#2918)

### PR DESCRIPTION
**Pull request by rxliuli**
fix https://github.com/vitest-dev/vitest/issues/2918

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
We need to clear extra source maps to reduce the payload.

**Comment by rxliuli** [comment]
> We need to clear extra source maps to reduce the payload.

This is the sourcemap string in the source code, which should not be removed from the original code. Also, I just updated the matching rule to not match the sourcemap in the string, but only remove the generated sourcemap.

For example, in the following code, the sourcemap string in foo function should not be deleted

```js
// /home/projects/vitest-dev-vitest-dq6zze/foo.ts
function foo(src) {
  return `//# sourceMappingURL=data:application/json;base64,${src}`;
}
Object.defineProperty(__vite_ssr_exports__, "foo", { enumerable: true, configurable: true, get(){ return foo }});

//# sourceMappingSource=vite-node
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQU8sU0FBUyxJQUFJLEtBQXFCO0FBQ3ZDLFNBQU8scURBQXFEO0FBQzlEO2lIQUFBIiwibmFtZXMiOltdLCJzb3VyY2VzIjpbIi9ob21lL3Byb2plY3RzL3ZpdGVzdC1kZXYtdml0ZXN0LWRxNnp6ZS9mb28udHMiXSwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGZ1bmN0aW9uIGZvbyhzcmM6IHN0cmluZyk6IHN0cmluZyB7XHJcbiAgcmV0dXJuIGAvLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247YmFzZTY0LCR7c3JjfWA7XHJcbn1cclxuIl0sImZpbGUiOiIvaG9tZS9wcm9qZWN0cy92aXRlc3QtZGV2LXZpdGVzdC1kcTZ6emUvZm9vLnRzIn0=
```

**Comment by sheremet-va** [comment]
> This is the sourcemap string in the source code, which should not be removed from the original code. Also, I just updated the matching rule to not match the sourcemap in the string, but only remove the generated sourcemap.

We should have a test that checks source map is removed correctly then.

**Comment by rxliuli** [comment]
> > This is the sourcemap string in the source code, which should not be removed from the original code. Also, I just updated the matching rule to not match the sourcemap in the string, but only remove the generated sourcemap.
> 
> We should have a test that checks source map is removed correctly then.

Later I try to add a unit test to test this match

**Comment by rxliuli** [comment]
> > This is the sourcemap string in the source code, which should not be removed from the original code. Also, I just updated the matching rule to not match the sourcemap in the string, but only remove the generated sourcemap.
> 
> We should have a test that checks source map is removed correctly then.

Relevant unit tests have been added

**Comment by rxliuli** [comment]
It seems that the main branch has some unit test bugs that prevent CI from passing

image

**Review by sheremet-va — APPROVED** [review]

**Pull request merged**
