### PR TITLE
fix(vite-node): remove suffix slash on file protocol for window

### PR DESCRIPTION
**Pull request by syi0808**
### Description
In window platform, dynamic import with file protocol are convert to request id and request id normalized by normalizeRequestId function.
normalizeRequestId function's return value with file protocol is like '/C:Users/user/workspace/file.js' in window, so fs can't resolve this absolute path because of suffix forward slash.

For that reason, when isWindow is true, i decided to remove the suffix slash. 

### before this pr
IMG_9441-min

### after this pr
IMG_9440-min

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

Fix: #6087

### CODE REVIEW

**Comment by syi0808** [comment]
Additional, vite-node hasn't test, so i don't add test for this changes. but is it better to add?

**Comment by sheremet-va** [comment]
I don't think this is the root of the problem, this code wasn't touched for a long time. We need to know why the issue happens when it happens. It worked in 1.6.0. We also need a new test case of course.

**Comment by syi0808** [comment]
> I don't think this is the root of the problem, this code wasn't touched for a long time. We need to know why the issue happens when it happens. It worked in 1.6.0. We also need a new test case of course.

I have trouble to add test. https://github.com/vitest-dev/vitest/pull/6109/commits/b6a34fa21bffe7a33f4000bda2aaf004cc1d8209
I dynamic import vite-node/utils, but isWindow not changed. It fixed by first process.platform.

And let's look for the reason why it worked in 1.6.0. The information I checked while debugging was generated from 2.0.0-beta.1, but the changes in 2.0.0-beta.1 did not seem to have much effect. I checked variously, such as node version and vite, but the only thing I found was the corresponding PR.

**Comment by sheremet-va** [comment]
> I dynamic import vite-node/utils, but isWindow not changed. It fixed by first process.platform.

1. You don't need to mock the platform, we are running tests on all platforms
2. You shouldn't test the function because that's not what this PR fixes - you need to test the dynamic import

**Comment by syi0808** [comment]
> > I dynamic import vite-node/utils, but isWindow not changed. It fixed by first process.platform.
> 
> 1. You don't need to mock the platform, we are running tests on all platforms
> 2. You shouldn't test the function because that's not what this PR fixes - you need to test the dynamic import with an absolute path (vite-node is just an implementation detail)

Thanks for guide. I remove util unit test and add integration test about write file and dynamic import.
And I've been debugging, but I can't find a good reason. What's certain is that 'fs.readFile('/C:/Users/user/workspace/file.js')' throws an error.

**Comment by syi0808** [comment]
I think failed test is not depend on this pr changes. So new added test is works as well and I'll keep looking for reasons.

**Comment by syi0808** [comment]
I found it @sheremet-va. this happen is because of https://github.com/vitest-dev/vitest/pull/5177.
In version 1.6.0 `server.watch.ignored` is exist. So it not cache fs method results that vite implements.
Bug version 2 `server.watch.ignored` is not exist because remove watchExclude. So it cache fs method results that vite implements.
File path resolving logic in vite fsUtils implemenet so, I don't know the details of the implementation but, file path resolving logic is certainly changed by `server.watch.ignored`.

Screenshot 2024-07-13 at 6 45 56 AM
Screenshot 2024-07-13 at 6 40 52 AM
Screenshot 2024-07-13 at 7 11 15 AM

**Comment by syi0808** [comment]
So I think this change can be resolved separately from the cause, so why not reflect it? Basically, the path with the slash in window is wrong.

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
LGTM!

**Pull request merged**
