### PR TITLE
feat!(vitest): add "vitest list" command to output test names

### LINKED ISSUE #2901: Add CLI command to output a list of tests for better testNamePattern usage
### Clear and concise description of the problem

When using `describe`, it can be hard to narrow tests based on files/describe blocks -- especially when test names within describe blocks / test files may be repeated. 

### Suggested solution

As a debug utility, it could be great to be able to output the list of tests without running them so that folks can better utilize `--testNamePattern`

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Closes #2901

This PR adds a new command:

```
vitest list
```

It outputs the list of tests that would be running with passed-down filters. For example, like this:

```
vitest list filename another-filename -t "some kind of filter"
```

By default, it just prints a list of names to stdout. You can pass down `--json` flag to output it as json (it will also include a filename as a separate field). `--json` flag also accepts a path to the file: `vitest list --json=./tests.json`

This PR also adds a new config option called `collectors` which has the same interface as a reporter - so you can collect tests in real-time (`onCollected` will be called after each test _file_ is collected). This will probably be useful for tools like VS Code extension.

To improve performance, Vitest ignores "isolate" flag (always set to `false`), unless it's overridden in CLI.

TODO:

- [ ] Update browser peer dependency
- [ ] Documentation

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
Currently, it cannot exit for some reason (investigating). The output itself is not here yet. A few questions, @NullVoxPopuli:

- Do we output the banner? ([RUN] Vitest 1.0.0)
- Do we output test names while collecting them?
- How does the finished output look like?

**Comment by NullVoxPopuli** [comment]
> Do we output the banner? 

seems fine for stdout

> Do we output test names while collecting them?

I don't think there is a need to stream any output if that's easier -- we wouldn't be running the tests themselves, so collecting everything to output at once should be _very fast_.

> How does the finished output look like?

Potentially: https://github.com/vitest-dev/vitest/issues/2901

**Comment by marilari88** [comment]
Hi @sheremet-va! As the Vitest adapter maintainer for Neovim, I was thrilled about this PR. It seems like a game-changer for resolving issues related to test discovery, especially for parameters tests.

Any chance you could provide a quick update on its status? I believe this integration is crucial for everyone developing tools upon Vitest. Your work is greatly appreciated!

**Comment by weilbith** [comment]
Why was this PR closed? 😕 
Vitest is version `2.0.0` now. 🙃

**Comment by sheremet-va** [comment]
It's implemented in another PR: https://github.com/vitest-dev/vitest/pull/6013

**Pull request closed without merging**
