### PR TITLE
feat: allow changing name pattern during watch mode

### LINKED ISSUE #658: Add `testNamePattern` to help's CLI input
### Clear and concise description of the problem

Similarly to Jest, it would be great if a user could **apply or change** `testNamePattern` while running:
- `vitest watch`

### Suggested solution

Same flow as in Jest:

1. while running `vitest watch`, a user clicks `h` to show help
2. user clicks `t` to apply or change the `testNamePattern`
3. user types pattern and clicks `Enter`
4. pattern for test names is applied

### Alternative

_No response_

### Additional context

Same applies to file name filtering that as of now doesn't exist in `vitest`, but does in `jest`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
Closes #658

### CODE REVIEW

**Comment by patak-dev** [comment]
I tested locally and I can't type the pattern once I select the option. I can only press enter.
The PATTERN label isn't visible due to contrast, at least in my terminal (that I think has a proper font and color theme)
image

**Comment by patak-dev** [comment]
About the wording, Jest uses "Press t to filter by a test name regex pattern.". Maybe we could also expand it to "Change test name pattern"? The `testNamePattern` casing looks a bit off in the middle of the other options.

**Comment by sheremet-va** [comment]
> I tested locally and I can't type the pattern once I select the option. I can only press enter. The PATTERN label isn't visible due to contrast, at least in my terminal (that I think has a proper font and color theme) image

Oh, I did too much refactoring 👀

**Comment by sheremet-va** [comment]
Changed the color to magenta
Снимок экрана 2022-02-20 в 18 59 37

**Comment by patak-dev** [comment]
Looks good now! And I can type. But if I press backspace it writes "backspace" and if I tried to use uppercase it doesn't let me. I was trying to write "JSON" to filter that one.

**Comment by sheremet-va** [comment]
> Looks good now! And I can type. But if I press backspace it writes "backspace" and if I tried to use uppercase it doesn't let me. I was trying to write "JSON" to filter that one.

Should be fixed 😃 
First time using this API!

**Review by patak-dev — APPROVED** [review]
Works great!

One thing about DX, maybe we shouldn't show the skipped tests when using this option, because if there are a lot of them you don't see the ones that were filtered (for example with JSON in the core tests)

**Comment by sheremet-va** [comment]
> Works great!
> 
> One thing about DX, maybe we shouldn't show the skipped tests when using this option, because if there are a lot of them you don't see the ones that were filtered (for example with JSON in the core tests)

I agree, but this is more about `testNamePattern` implementation

**Pull request merged**
