### PR TITLE
feat: make `isolate` default to false

### PR DESCRIPTION
**Pull request by antfu**
Discussed with the team and here is the gist of the switch:

- An isolated env is ideal, but it also means you need to **execute all the dependencies for every file** in order to get a clear state in a separate worker. With the cost of performance.
- For most cases, we do unit tests that have no or minimal side-effects, the isolation might not be necessary.
- We should advocate the tests to be side-effects free (with proper mocking) when it's possible.

Instead of opt-out, we think it's better to be opt-in for ppl who absolutely need the isolation and willing to pay the extra performance cost for it.

### CODE REVIEW

**Review by patak-dev — APPROVED** [review]

**Comment by edimitchel** [comment]
I would like to suggest to add a new kind of [describe](https://vitest.dev/api/#describe) to let explicitly isolate one test (is it possible?).

```ts
describe.isolate('Component rendering', () => {
  // ...
});
```

**Comment by antfu** [comment]
We could probably use some magic comments as we have for the environment.

```ts
// @vitest-environment jsdom
// @vitest-isolated true
```

**Comment by dominikg** [comment]
I like the idea of an annotation or a new kind. But imho the default behavior should be safe, not fast and lose. 
People can opt-in to that when they're aware of the consequences.

**Comment by sheremet-va** [comment]
> For most cases

Not sure if this is true at the moment? My experience has been that people come from Vite testing their frontend code. Unfortunately a lot of frontend libraries rely on a global state or add global event listeners and so on. People might event not realize it.

As I said in the internal discussion, I prefer isolation enabled with a paragraph in docs discussing performance issues with the approach and give common patterns to resolve them (for example, if you run only unit tests, disable isolation, and if you have another folder or smth to run integration tests, consider enabling isolation).

Disabling this can lead to "debug hell", when errors appear out of nowhere, and people might get confused.

**Pull request closed without merging**
