### PR TITLE
refactor(coverage): move common parts to `vitest` package

### PR DESCRIPTION
**Pull request by AriPerkkio**
### Description

Now that coverages packages don't have to maintain compatibility with previous `vitest` versions in same major (https://github.com/vitest-dev/vitest/pull/5208), we can move more reusable code into `vitest` package. This is only refactoring to reduce duplication.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by hi-ogawa — APPROVED** [review]
Looks good!

Just to confirm, is it intentional to not move magicast's `parseModule` to `BaseCoverageProvider.updateThresholds`? If we move it, then `magicast` dependency also has to go to main `vitest` package, so maybe that's a slight concern.

**Comment by AriPerkkio** [comment]
> Just to confirm, is it intentional to not move magicast's `parseModule` to `BaseCoverageProvider.updateThresholds`?

Yes exactly - we want to avoid having it as dependency on `vitest` package: https://github.com/vitest-dev/vitest/pull/4442#discussion_r1390268622.
It cannot even be a devDependency for types: https://github.com/vitest-dev/vitest/pull/4442#discussion_r1395438550.

**Comment by hi-ogawa** [comment]
Thanks for the links. Good to know it was already discussed before :+1:

**Comment by AriPerkkio** [comment]
Now that _breaking changes_ inside same major version are fine this kind of issues can come up https://github.com/vitest-dev/vitest/discussions/5310 🤷‍♂️

**Pull request merged**
