### PR TITLE
fix: correctly render ansi diff

### PR DESCRIPTION
**Pull request by so1ve**
close https://github.com/vitest-dev/vitest/issues/3675

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Can you add a test for this? We have cypress tests in UI package.

**Comment by sheremet-va** [comment]
> I'd like to add a test for this but... I'm not familiar with cypress, and I'm not sure where to add these tests. Any suggestions?

You can look at other tests. To see the script to run it, you can look into package.json

**Comment by nasso** [comment]
is anything blocking this?

**Comment by so1ve** [comment]
@nasso Yes, missing tests. I'm unfamiliar to e2e tests, so…

**Pull request merged**
