### PR TITLE
docs: add team emeriti and update the sidebar and navigation

### PR DESCRIPTION
**Pull request by sheremet-va**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by patak-dev** [comment]
At least in the preview link, the avatars for team emeriti are 404 
image

**Review by patak-dev — DISMISSED** [review]

**Comment by userquin** [comment]
We should switch to X...

**Review by userquin — DISMISSED** [review]

**Comment by userquin** [comment]
I'm going to add some styles for new team cards trying to align vertically text lines, old styles using small and now medium (in this PR or in another one if merged)

**Comment by sheremet-va** [comment]
Feel free to push to this branch

**Pull request merged**
