### PR TITLE
Add info how to setup debugging in VSCode

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Just some basic documentation on how to setup a launch configuration to debug the currently selected test file in vitest.

Happy to expand if there are suggestions

### CODE REVIEW

**Comment by mitchelvanbever** [comment]
Awesome this seems like a great starting point for anyone to dive deeper!

Could you add it to the navigation so it becomes visible in the sidebar (located in `docs/.vitepress/config`)?

**Comment by JakeGinnivan** [comment]
@mitchelvanbever done, just assumed it was by convention, bad assumption :)

**Review by mitchelvanbever — APPROVED** [review]

**Review by patak-dev — APPROVED** [review]

**Comment by fabiopand** [comment]
I copied the [vue example](https://github.com/vitest-dev/vitest/tree/main/examples/vue), and tried with this config, but for some reason it´s not working.

image

**Comment by fabiopand** [comment]
`npx vitest run` command is ok.

image

**Comment by IceToast** [comment]
I do experience the same error as @fabiopand

**Comment by JakeGinnivan** [comment]
Ah, I use a mac. Someone will need to update the docs so it works for both mac and windows. Happy to test out

**Pull request merged**
