### PR TITLE
chore: add simple benchmark for comparison with jest

### PR DESCRIPTION
**Pull request by Demivan**
After this is merged, adding `/bench` or `/benchmark` comment on a pull request will run the benchmark. After benchmark finishes, results will be posted as a comment.
Example: https://github.com/Demivan/vitest/pull/4#issuecomment-1003759902

It is possible to run benchmark locally too:
```
cd bench
pnpm i
pnpm bench
```

For some reason when running jsdom and having a lot of test files Vitest fails. So I switched to happy-dom for now. Will investigate this issue later.

### CODE REVIEW

**Comment by patak-dev** [comment]
Should we already use a standard benchmark for test runners instead of a simple vue example? I think you mention some options in Vitest Dev. Could you link them here?

**Comment by Demivan** [comment]
https://github.com/EvHaus/jest-vs-jasmine - is the benchmark that I mentioned. It is React focused - not sure we need it.

**Comment by antfu** [comment]
I feel we should reuse the tests under `test/` to the bench as we will have different results for different scenarios.

**Review by patak-dev — APPROVED** [review]

**Comment by patak-dev** [comment]
Approved in case we want to keep working in future PRs

**Comment by Demivan** [comment]
> I feel we should reuse the tests under `test/` to the bench as we will have different results for different scenarios.

Agree, but while setting up Vitest is simple, making those tests work in Jest is hard. Need to add a lot of Jest packages and configuration.

Can this PR be just an initial implementation that we will improve on later? I want to look into jsdom failure and current bottleneck with Vue tests. I think Vue tests will be the most common scenario for Vitest anyway.

**Comment by Demivan** [comment]
@antfu @patak-dev I have changed benchmark tests to use test files from `test/vue` folder.
We can enable `test/core` tests later too. But will need to enable `global: true` for them, so they don't import Vitest directly. And add Jest specific config and packages to the bench.

**Comment by antfu** [comment]
Looks great, thanks!

**Pull request merged**
