### PR TITLE
fix(spy)!: spyOn reuses mock if method is already spyed on

### LINKED ISSUE #6419: isMockedFunction returns wrong value after object is spied on twice
### Describe the bug

Spy on an object twice and call `restoreAllMocks`, then `isMockedFunction` still thinks that it is a mock function.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-bhbdof?file=test%2Fbasic.test.ts

```
import { describe, expect, it, vi } from "vitest";

const fooService = { foo: () => "foo" };
describe("fooService", () => {
  describe("foo", () => {
    it("is not a mock functon after 1 spy", () => {
      vi.spyOn(fooService, "foo").mockImplementation(() => "bar");
      vi.restoreAllMocks();
      expect(vi.isMockFunction(fooService.foo)).toBe(false);
    });
    it("it not a mock function after 2 spys", () => {
      vi.spyOn(fooService, "foo").mockImplementation(() => "bar");
      vi.spyOn(fooService, "foo").mockImplementation(() => "bar");
      vi.restoreAllMocks();
      expect(vi.isMockFunction(fooService.foo)).toBe(false);
    });
  });
});
```
```
 ❯ test/fooService.test.ts (2)
   ❯ fooService (2)
     ❯ foo (2)
       ✓ is not a mock functon after 1 spy
       × it not a mock function after 2 spys

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/fooService.test.ts > fooService > foo > it not a mock function after 2 spys
AssertionError: expected true to be false // Object.is equality

- Expected
+ Received

- false
+ true

 ❯ test/fooService.test.ts:15:49
     13|       vi.spyOn(fooService, "foo").mockImplementation(() => "bar");
     14|       vi.restoreAllMocks();
     15|       expect(vi.isMockFunction(fooService.foo)).toBe(false);
       |                                                 ^
     16|     });
     17|   });
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 2.0.5 
    vite: latest => 5.4.2 
    vitest: latest => 2.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #6465: Latest version of tinyspy (3.0.1) causes a `Cannot redefine property: mock` when trying to spyOn an object multiple times
### Describe the bug

Renovate caught this issue in our CI (https://github.com/apify/apify-cli/pull/636). It seems like the latest version of tinyspy (3.0.1) causes some issues when trying to spy on and mock an object's method multiple times. This issue doesn't repro on tinyspy 3.0.0 (and somehow I was also unable to reproduce this with tinyspy directly...)

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-uuvjoy

### System Info

```shell
System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 150.05 MB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.volta/tools/image/node/20.17.0/bin/node
    Yarn: 4.4.1 - ~/.volta/tools/image/yarn/4.4.1/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/node/20.17.0/bin/npm
    bun: 1.1.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 18.0
  npmPackages:
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #6419 
Fixes #6465

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
@hi-ogawa need heelp

**Comment by hi-ogawa** [comment]
I don't think we need to change automocker since `const original = this[key]` is not an owned property, so `spyOn` can ignore it and add the new spy as owned prop.
This means that reusing `spyOn` only happens for owned prop, but that behavior is probably reasonable.

**Comment by dskloetd** [comment]
I just ran into this after test failures from upgrading our vitest dependency. And I've got to say it's rather confusing to create a brand new spy and
```
expect(spy).toBeCalledTimes(0);
```
immediately failing. Pretty disappointed with this change.

**Comment by hi-ogawa** [comment]
@dskloetd You might be happy with a follow up fix https://github.com/vitest-dev/vitest/pull/7359.

**Pull request merged**
