### PR TITLE
refactor(vitest): call hoistMocks in directRequest instead of mocks plugin

### PR DESCRIPTION
**Pull request by Dunqing**
### Description

close: #4619

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
> To fix the bug, as I already said, we need to process property access the same way Vite does for SSR. That way we can keep it working both in browser and Node.js.

We actually already have code for this in the browser package. It does a similar thing if `hijackESM` is enabled.

**Comment by Dunqing** [comment]
> To fix the bug, as I already said, we need to process property access the same way Vite does for SSR. That way we can keep it working both in browser and Node.js.

I see. But it can be complicated to deal with

**Comment by sheremet-va** [comment]
> But it can be complicated to deal with

I mean, we already have the code. How hard can it be 😄

**Comment by Dunqing** [comment]
> I mean, we already have the code. How hard can it be 😄

Ah, I just saw it. I have another question, can we transform only the import source that is mocked?

**Comment by Dunqing** [comment]
> > I have another question, can we transform only the import source that is mocked?
> 
> Not sure what you mean. We only transform the file that calls `vi.mock`

What I mean is that imports without mock should be filtered here.

https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/hoistMocks.ts#L103-L115

It looks like this.
```ts
import a from './a'
import b from './b' // should be filtered out because here doesn't call vi.mock('./b');
vi.mock('./a')

```

**Comment by Dunqing** [comment]
I will refer to `hijackESM` to solve this problem

**Pull request closed without merging**
