### PR TITLE
docs: Update common-errors to include dynamic import aliases

### PR DESCRIPTION
**Pull request by kamilogorek**
Since Vite 2.0 `vi.mock` can accept `import()` as the first argument to detect which module to be mock. This however won't work with aliased paths, which can confuse some people.

I believe this is not solvable at the moment, as this is not a Vitest, but rather TypeScript shortcoming.

### CODE REVIEW

**Comment by kamilogorek** [comment]
Not sure if inline diff-view can be used here, as CI fails to parse the code correctly. Might need to go back to 2 separate blocks.

**Comment by sheremet-va** [comment]
This is not true, it can be used with aliased paths

**Comment by kamilogorek** [comment]
Here's a repro for this issue https://github.com/kamilogorek/vitest-dynamic-import-mock/

I'm more than happy to be corrected, as it'd be lovely to use it in such form :)

image

**Comment by sheremet-va** [comment]
> Here's a repro for this issue [kamilogorek/vitest-dynamic-import-mock](https://github.com/kamilogorek/vitest-dynamic-import-mock/)
> 
> I'm more than happy to be corrected, as it'd be lovely to use it in such form :)

The `Cannot find module` issue in the documentation refers to the runtime error. It is not related to types, so adding this paragraph is confusing to me - maybe the documentation does a poor job at explaining it.

The issue you are experiencing is the opposite - TypeScript shows a type error, but code works at runtime, This is related to how TypeScript works and not to how Vitest works, so I don't think it has a place in our documentation

**Comment by kamilogorek** [comment]
Correct, that's why I mentioned

> this is not a Vitest, but rather TypeScript shortcoming.

I'm perfectly fine closing this PR if the team decides so, no worries :)

**Comment by sheremet-va** [comment]
> Correct, that's why I mentioned
> 
> > this is not a Vitest, but rather TypeScript shortcoming.
> 
> I'm perfectly fine closing this PR if the team decides so, no worries :)

I think we can add this note to the mocking page (https://vitest.dev/api/vi.html#vi-mock) when `vi.mock(import())` is introduced

**Comment by kamilogorek** [comment]
Reworded and moved to the `vi.mock` docs instead. Didnt use a `warning` block as there would be 3 consecutive warnings which looked odd.

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
Thank you!

**Pull request merged**
