### PR TITLE
docs: use `VPTeamMembers` component from `VitePress`

### PR DESCRIPTION
**Pull request by userquin**
This PR includes:
- update `VitePress` to `alpha-4`
- fix some color contrast on `::: tip` and gray cards (home page for example)
- switch Matías and Vlad team cards (request comes from Matías), also added a shield in Vlad card
- update core team members module to match `SocialLink` in `VitePress` 

I'll try to align entries on core team members cards via css styles.

### CODE REVIEW

**Review by patak-dev — APPROVED** [review]

**Comment by antfu** [comment]
The sponsor links did not show up 🤔

**Comment by userquin** [comment]
> The sponsor links did not show up 🤔
something related with the PWA?
https://streamable.com/mvys0m

**Comment by patak-dev** [comment]
It worked for me in an incognito window, but I also didn't see them now with my logged user. So looks like it is PWA related

**Comment by userquin** [comment]
> It worked for me in an incognito window, but I also didn't see them now with my logged user. So looks like it is PWA related

Can you check if the link (on mouseover) are ok? Chrome and Firefox just show the correct links for me: try reloading the page

**Comment by patak-dev** [comment]
I don't see the links, and I tried reloading the page.

**Comment by userquin** [comment]
I'll fix the PWA

**Comment by userquin** [comment]
I need to add some images to the PWA, for example the screenshots for UI.

**Comment by userquin** [comment]
added offline support for external images and the `Inter`  font (being used by Vitepess?).

**Comment by patak-dev** [comment]
Still not there, even after cleaning the data. The link is there though, maybe an issue with styles? Maybe it is about the changes you added to support better alignment?

image

**Comment by userquin** [comment]
> Still not there, even after cleaning the data. The link is there though, maybe an issue with styles? Maybe it is about the changes you added to support better alignment?
> 

It seems a problem with the `ab block` addon: it works in Windows using Edge, Chrome, Chrome Canary and Firefox, and also on Safari in MacOS.

I'm fixing it...

**Comment by patak-dev** [comment]
Works now after clearing the site data 👍🏼

**Pull request merged**
