### PR TITLE
Update workspace.md

### PR DESCRIPTION
**Pull request by kylecoberly**
Fix typo

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
There is nothing incorrect here.

**Comment by kylecoberly** [comment]
It's calling `mergeConfig` on a config and a project, which the type server said wasn't allowed (and doesn't make sense). Shouldn't it be merging a config with another config?

**Comment by sheremet-va** [comment]
> It's calling `mergeConfig` on a config and a project, which the type server said wasn't allowed (and doesn't make sense). Shouldn't it be merging a config with another config?

`defineProject` is just a type hint for the config. It removes some properties from the `test` object, you absolutely should use it over `defineConfig` for better type safety.

**Comment by kylecoberly** [comment]
It doesn't appear to be in the signature for `mergeConfig`:

image

image

There isn't a problem if I use `defineConfig`:

image

Is this a problem with the actual signature?

**Pull request closed without merging**
