### PR TITLE
docs: expect API

### PR DESCRIPTION
**Pull request by sheremet-va**

### CODE REVIEW

**Review by dammy001 — COMMENTED** [review]
@sheremet-va should I join you on adding examples to this APIs?

**Comment by sheremet-va** [comment]
> @sheremet-va should I join you on adding examples to this APIs?

Sure, you can help! I've devided matchers by sections. You can take snapshots and asymmetric matchers for now

**Comment by dammy001** [comment]
Alright 💪🏾

**Comment by sheremet-va** [comment]
First section of docs is covered. I think it will be easier to review if if we can split the sections.

**Comment by dammy001** [comment]
@sheremet-va I'll have to point my branch to main then for other APIs

**Pull request merged**
