### PR TITLE
feat(types): add generic parameter to toMatchObject

### PR DESCRIPTION
**Pull request by jgoux**
I often use this generic parameter with Jest to have autocompletion on values to match, example : 
```ts
  expect(response).toMatchObject<
    _.PartialDeep<GraphQLSchema.AnnotateFileResult>
  >({
    __typename: "AnnotateFileErrors",
    errors: [
      {
        __typename: "FileFormatNotSupported",
      },
    ],
  });
});
```

One DX improvement I made compared to Jest's generic is that I apply the `DeepPartial` helper by default so the user doesn't have to think about it as we're always matching partial objects.

[Here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIhFgAoEMBOwCWyA2AeAKgHxQC8U+UEAHsBAHYAmAzlAPYBGAVhAMbBQB+KAG8AUFAlQA2gGkoGOlADWEEKwBm5ALoCAXLHhI0mHAVlbCAblEBfKPvzXRDXtjTR1AVzp8MrRcCsALLIwDwAFgDyXLzABJQ09MxsMXyEABTUkHwQDPpwCCjoWHhEAJT6AG6sGAxOgSFhUanA6QBEdKz8yIoc3HxtZdYNoRHR-a0ALABMQ6IjTeOx6cJQ6qys+m3hyJXQyFB0GDzQAO7wKoxtUDZzC2MtuFKr65tQTMCoCgDmNwA0Iig7DQ+g+XzovxsFnSzzWGy2Oz2UAORxOUHOEEuDGuULuwVGzQmTxe8Penx+-0BwNQoPJEJu0Nh1IRu32h2OZwuSRxWjxjQeRNWzLJ4O+ANetNFAOon2Q+nYG2wEB6NwyJLe21ZyPZaIxWJxfIJSz4uCFyAAXpKKTY1XCNYi2ajOZjuTchkA) is a usage example on TypeScript Playground.

### CODE REVIEW

**Comment by sheremet-va** [comment]
I'm not sure if `DeepPartial` is expected behaviour. Jest doc says: `Optionally, you can provide an object to use as Generic type for the expected value. This ensures that the matching object matches the structure of the provided object-like type`

Indeed, what if I want to add type and check if it's fully compatible with the passed object? `DeepPartial` will pass even with `{}`

**Comment by jgoux** [comment]
@sheremet-va IMHO the types should reflect the runtime behaviour, if they are lying about it then they can't be trustee to keep the code safe. 

toMatchObject is for matching a subset of the object. For an exact match there is toEqual (which could take a generic as well, without DeepPartial).

**Comment by sheremet-va** [comment]
> @sheremet-va IMHO the types should reflect the runtime behaviour, if they are lying about it then they can't be trusted to keep the code safe.
> 
> toMatchObject is for matching a subset of the object. For an exact match there is toEqual (which could take a generic as well, without DeepPartial).

But this generic exists to ensure the type for `toMatchObject` is equal to passed object. If it was as you say, we would use type that was passed to `expect`.

**Comment by jgoux** [comment]
> > @sheremet-va IMHO the types should reflect the runtime behaviour, if they are lying about it then they can't be trusted to keep the code safe.
> > toMatchObject is for matching a subset of the object. For an exact match there is toEqual (which could take a generic as well, without DeepPartial).
> 
> But this generic exists to ensure the type for `toMatchObject` is equal to passed object. If it was as you say, we would use type that was passed to `expect`.
> 
> `DeepPartial` will never give an error, so providing anything to `toMatchObject` would be useless.

I don't really understand this reasoning. In the usage of `toMatchObject` what I always want is autocompletion + avoiding typos when defining a partial matching object against the value I pass in expect(). Again if the point of the runtime behavior is matching an object **partially** then I expect my type to reflect this usage. If writing `expect(someObject).toMatchObject<{ foo: boolean }>({})` is accepted at runtime then TypeScript should accept it as well. I read this assertion as "I expect myObject of type T to match at least this subset", which is exactly what is happening at runtime, and there is a greater chance in my experience that you will have the type T already provided by your library/API than a custom type U which would be a handmade subset of T (because if it's not a subset then you should definitely use `toEqual`).

I understand that the current `@types/jest` implementation differs and I thought it was a good opportunity to provide a better default. If the goal is 100% backward compatibility then I'll remove the `PartialDeep` (and use module augmentation in my own projects to provide it as I think it's the most sensitive default 😄).

@patak-dev could you tell us which solution you want to see implemented for vitest?

**Pull request closed without merging**
