### PR TITLE
feat(runner): add "queued" state

### LINKED ISSUE #6915: Reporter API: report files before collection
### Clear and concise description of the problem

There is no way for a reporter to know if a file is currently being collected. If the collection phase is slow (e.g. transforms 100000 files due to barrel files), end users have no idea what is going on. Reporters cannot inform user about slow files. 

### Suggested solution

Before collection for a file starts, inform reporters on `onTaskUpdate` hook that file is in queue. It could be something like `File & { mode: 'queued' }`. Next expected state after this is `run`.

Somewhere around here:

https://github.com/vitest-dev/vitest/blob/0b08bc11c42f57fc589760f226ce840837fe2f7a/packages/runner/src/collect.ts#L31-L35

### Alternative

_No response_

### Additional context

The summary of https://github.com/vitest-dev/vitest/pull/6893 could display queued files even before they start running. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #6915

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
> Note: doesn't seem like it's working as I expected in a real project - https://github.com/zammad/zammad

Tested and it now looks very nice 👌🏻

**Comment by sheremet-va** [comment]
> We should probably hide test count when `testFile.total` is `0`:

Do you want to just remove it without having any labels?

```
> fixtures/example.test.ts
> fixtures/example.test.ts (0/0)
> fixtures/example.test.ts [queued]
> fixtures/example.test.ts (queued)
```

**Comment by sheremet-va** [comment]
@AriPerkkio any feedback? 👀

**Comment by AriPerkkio** [comment]
Testing this on Vite's `pnpm test-serve`, something breaks test count. There's `7/0` visible:

image

**Comment by sheremet-va** [comment]
> Testing this on Vite's `pnpm test-serve`, something breaks test count. There's `7/0` visible:

I will look into it. Any feedback on https://github.com/vitest-dev/vitest/pull/6931#issuecomment-2531010542 ?

**Comment by AriPerkkio** [comment]
> I will look into it. Any feedback on https://github.com/vitest-dev/vitest/pull/6931#issuecomment-2531010542 ?

If label doesn't cause too much flickering, sure. Maybe the icon could also be different, though I'm not sure what color and shape would work best.

**Comment by sheremet-va** [comment]
> Testing this on Vite's `pnpm test-serve`, something breaks test count. There's `7/0` visible:

Should be fixed

**Comment by AriPerkkio** [comment]
Still there 🤔 
image

**Comment by sheremet-va** [comment]
Added another workaround. I agree would be nice to have this statistics in test suites themselves :D

Maybe we can track it in the`state`

**Comment by AriPerkkio** [comment]
It's still there. Here's the PR on top, `main` below:

**Comment by sheremet-va** [comment]
I can't really reproduce it - I've run it on the vite repo several times.

**Comment by AriPerkkio** [comment]
Does it help reproducing if you add this in `playground/css/__tests__/same-file-name/css-same-file-name.spec.ts`?

```ts
// after all other code

test('temp', async () => {
  await new Promise((r) => setTimeout(r, 10_000))
})
```

**Comment by AriPerkkio** [comment]
Adding this in `createSummary` reveals the erroneous reports:

```ts
      if (testFile.completed > testFile.total) {
        this.ctx.logger.log(`Error: ${testFile.completed} > ${testFile.total} ${testFile.filename}`)
      }
```


https://github.com/vitest-dev/vitest/blob/4e60333dc7235704f96314c34ca510e3901fe61f/packages/vitest/src/node/reporters/summary.ts#L269-L271

We need might need to extend the check to 

```diff
- if (!stats) {
+ if (!stats || stats.total === 0) {
```

This is all related to the fact that test runners can skip test and test file phases, e.g. test can be reported as finished even though it was never reported to start. 

I'll take closer look at this later today.

**Comment by AriPerkkio** [comment]
Verified fix from f91a5f7 in Vite's `pnpm test-serve`. ✅ 

During https://github.com/vitest-dev/vitest/pull/7069 we'll be fixing this "prevent reporting tests finished if they haven't even been reported as starting" properly. We'll need some state logic in TaskParser (or in it's successor). Then we can remove some complex logic from `summary.ts` and `dot.ts` reporters.

**Review by AriPerkkio — APPROVED** [review]

**Pull request merged**
