### PR TITLE
fix: add throat when running spec files

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes `VITETS_POOL_ID` logic.

I noticed no performance differences with this.

I _think_ this might also help with segfalts and Node errors? I have a feeling that running them all might cause it, but I don't have anything to back up that claim.

### CODE REVIEW

**Comment by antfu** [comment]
https://www.npmtrends.com/p-limit-vs-p-throttle-vs-promise-throttle-vs-throat

Maybe p-limit?

**Comment by sheremet-va** [comment]
> https://www.npmtrends.com/p-limit-vs-p-throttle-vs-promise-throttle-vs-throat
> 
> Maybe p-limit?

Sure. Replaced it. Also added comment to PR, if you didn't notice.

**Comment by sheremet-va** [comment]
Closed in favor of #1482

**Comment by antfu** [comment]
I guess tinypool already has the queueing mechanism, probably this might be redundant. About the Segfault, I guess it's about some deep bug of Node, where even if this makes it less likely to appear (I doubt tho), it doesn't really fix the root cause. 🤔

**Comment by sheremet-va** [comment]
> It has, but we can't hook up to it.

Maybe we can add this functionality to `tinypool`?

> Doesn't hurt to try.

`react-enzym` failed once in the new PR, but fixed in the second one. I fear this change might introduce flaky tests now :P

**Pull request closed without merging**
