### PR TITLE
feat: VITEST_POOL_ID cannot be the same between different running specs

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes `VITETS_POOL_ID` logic.

### CODE REVIEW

**Comment by sheremet-va** [comment]
@Aslemammad tests are not exiting, if I import `tinypool` directly inside a worker 🤔

**Comment by sheremet-va** [comment]
> @sheremet-va Can I continue the work here?

Sure

**Comment by Aslemammad** [comment]
@sheremet-va Could you please try updating tinypool (patch, I released)

**Comment by sheremet-va** [comment]
> @sheremet-va Could you please try updating tinypool (patch, I released)

updated

**Review by Aslemammad — APPROVED** [review]

**Review by antfu — APPROVED** [review]

**Pull request merged**
