### PR TITLE
feat: add `maxConcurrency` option

### LINKED ISSUE #1212: max concurrency setting for test.concurrent
### Clear and concise description of the problem

If you run a large number of tests with bottlenecks, such as database access, in `test.concurrent`, each test will affect each other and take time.

Also, in some cases, such as CI, you may want to tweak performance so that it does not become too heavy.

### Suggested solution

How about adding an option `maxConcurrency` to config to limit the number of concurrent tests to be run by `test.concurrent`?
```js
export default defineConfig({
  test: {
    maxConcurrency: 5,
  },
})
```

The implementation is to queue the tests for `test.concurrent` once, and run them without exceeding `maxConcurrency`.

Jest addresses these issues with an option `maxConcurrency` that allows you to tweak concurrent.
https://jestjs.io/ja/docs/configuration#maxconcurrency-number
> A number limiting the number of tests that are allowed to run at the same time when using test.concurrent. Any test above this limit will be queued and executed once a slot is released.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
Closes #1212

### CODE REVIEW

**Comment by antfu** [comment]
It's better to release this with the next minor bump.

**Comment by sheremet-va** [comment]
> It's better to release this with the next minor bump.

I am waiting for you to review `--shard` before releasing a new version 😄

**Comment by gajus** [comment]
Is there a way to set this globally?

```
Usage:
  $ vitest run [...filters]

Options:
  -r, --root <path>                      Root path
  -c, --config <path>                    Path to config file
  -u, --update                           Update snapshot
  -w, --watch                            Enable watch mode
  -t, --testNamePattern <pattern>        Run tests with full names matching the specified regexp pattern
  --dir <path>                           Base directory to scan for the test files
  --ui                                   Enable UI
  --open                                 Open UI automatically (default: !process.env.CI))
  --api [api]                            Serve API, available options: --api.port <port>, --api.host [host] and --api.strictPort
  --threads                              Enabled threads (default: true)
  --single-thread                        Run tests inside a single thread, requires --threads (default: false)
  --experimental-vm-threads              Run tests in a worker pool using VM isolation (default: false)
  --experimental-vm-worker-memory-limit  Set the maximum allowed memory for a worker. When reached, a new worker will be created instead
  --silent                               Silent console output from tests
  --hideSkippedTests                     Hide logs for skipped tests
  --isolate                              Isolate environment for each test file (default: true)
  --reporter <name>                      Specify reporters
  --outputFile <filename/-s>             Write test results to a file when supporter reporter is also specified, use cac's dot notation for individual outputs of multiple reporters
  --coverage                             Enable coverage report
  --run                                  Disable watch mode
  --mode <name>                          Override Vite mode (default: test)
  --globals                              Inject apis globally
  --dom                                  Mock browser api with happy-dom
  --browser [options]                    Run tests in the browser (default: false)
  --environment <env>                    Specify runner environment, if not running in the browser (default: node)
  --passWithNoTests                      Pass when no tests found
  --logHeapUsage                         Show the size of heap for each test
  --allowOnly                            Allow tests and suites that are marked as only (default: !process.env.CI)
  --dangerouslyIgnoreUnhandledErrors     Ignore any unhandled errors that occur
  --shard <shard>                        Test suite shard to execute in a format of <index>/<count>
  --changed [since]                      Run tests that are affected by the changed files (default: false)
  --sequence <options>                   Define in what order to run tests (use --sequence.shuffle to run tests in random order, use --sequence.concurrent to run tests in parallel)
  --segfaultRetry <times>                Return tests on segment fault (default: 0) (default: 0)
  --no-color                             Removes colors from the console output (default: true)
  --inspect                              Enable Node.js inspector
  --inspect-brk                          Enable Node.js inspector with break
  --test-timeout <time>                  Default timeout of a test in milliseconds (default: 5000)
  --bail <number>                        Stop test execution when given number of tests have failed (default: 0)
  --retry <times>                        Retry the test specific number of times if it fails (default: 0)
  --diff <path>                          Path to a diff config that will be used to generate diff interface
```

We have a problem where vitest hogs too much CPU and ends up suffocating database operations (which is hosted on the same machine). I am not clear on how to tell Vitest to at most parallelize 80% CPU worth of threads.

**Comment by gajus** [comment]
Found it:

```diff
+ import os from 'node:os';
import path from 'node:path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  test: {
    deps: {
      interopDefault: true,
    },
+    maxThreads: Math.ceil(os.cpus().length * 0.5),
    mockReset: true,
    outputFile: './src/__generated__/vitest/results.xml',
    reporters: ['verbose', 'junit'],
    testTimeout: 60_000,
  },
});
```

**Comment by gajus** [comment]
On a related note, I am not sure if defaulting to 100% of the CPUs is a great idea. It diminishes test stability.

**Pull request merged**
