### PR TITLE
fix(ui): Use web hash history in ui (fix #3481)

### LINKED ISSUE #3481: Can't serve @vitest/ui report on a subpath
### Describe the bug

Upload a vitest/ui generated report  to a subpath in an HTTP server (And make sure the `.gz` file is served with an `Content-Type: application/gzip`, or `Content-Encoding: gzip` which might also work). You will get a blank page. The report only works at the root path of a site, disallowing uploading it somewhere for others to view. (e.g. From CI).

That is, it works when the URL is:
http://somewhere.com/

But fails if it is:
http://somewhere.com/vitest-report/

Such reports are very useful to upload to a shared server for others to easily view from CI, but they need to handle being served from any subpath for this to work properly.

### Reproduction

Generate any @vitest/ui report, and use `caddy run` (Install caddy) with the following `Caddyfile` and the report in a subdirectory.

```caddyfile
http://localhost:8080

@gz {
	path *.gz
}

header @gz Content-Type application/gzip

file_server browse
```

e.g.
* Caddyfile
* report/
    * index.html

And try to access http://localhost:8080/report/, you will get a blank page, no errors in the console.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 57.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.1.0 
    @vitest/ui: ^0.31.2 => 0.31.2 
    vite: ^4.1.4 => 4.2.1 
    vitest: ^0.31.2 => 0.31.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by segevfiner**
fix #3481

### CODE REVIEW

**Comment by davidbonnet** [comment]
This is a nice workaround. Note that refreshing a page leads again to a blank page (but that's an issue with `createWebHashHistory`).

**Comment by segevfiner** [comment]
That's weird. Shouldn't it read the hash from the URL and work correctly
after a refresh?

בתאריך יום ה׳, 15 ביוני 2023, 15:53, מאת David Bonnet ‏<
***@***.***>:

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Can confirm that it stops working even in dev after page is refreshed.

**Comment by segevfiner** [comment]
Wasn't able to reproduce the failure.

I did:
1. `pnpm build` to build vitest
2. Ran `pnpm test -- --reporter html` in `examples/basic`
3. Ran `pnpm vite preview --outDir html` in `examples/basic`
4. Opened the browser, navigated to one of the tests, hit refresh, it loaded successfully back on this test, the URL uses web hash history as expected.

Was there some bug in `createWebHashHistory` that might have been fixed in the mean time and have been brought in by the merge 😕

**Comment by minwe** [comment]
> Can confirm that it stops working even in dev after page is refreshed.

1. config HTML as test reporter
```
export default defineConfig({
  test: {
    reporters: [
      'default',
      'html',
    ],
  }
});
```
2. run `vitest run --coverage`, vitest will output HTML reporter in `{projectRoot}/html`
3. start HTTP server like https://www.npmjs.com/package/http-server in project root
4. open `http://127.0.0.1:8080/html`, you will get a white page, test reporter content does not render

**Comment by segevfiner** [comment]
> > Can confirm that it stops working even in dev after page is refreshed.
> 
> 1. config HTML as test reporter
> 
> ```ts
> export default defineConfig({
>   test: {
>     reporters: [
>       'default',
>       'html',
>     ],
>   }
> });
> ```
> 
> 2. run `vitest run --coverage`, vitest will output HTML reporter in `{projectRoot}/html`
> 3. start HTTP server like https://www.npmjs.com/package/http-server in project root
> 4. open `http://127.0.0.1:8080/html`, you will get a white page, test reporter content does not render

That happened to me when it used the current @vitest/ui instead of the version in this pull request. I was able to reproduce the refresh issue finally. Now to figure out what causes it cause it kinda looks like an issue in vue-router itself.

**Comment by segevfiner** [comment]
Found it @vitest/ui also uses `useUrlSearchParams`, which needs to be configured with the correct mode to match the mode of vue-router. It works now after refresh @davidbonnet @sheremet-va

**Review by sheremet-va — APPROVED** [review]
Looks good to me 👍🏻

**Pull request merged**
