### PR TITLE
feat: improve expectTypeOf error messages

### PR DESCRIPTION
**Pull request by mmkal**
### Description

Update expect-type version to the prerelease from https://github.com/mmkal/expect-type/pull/16 - it should make error messages much better. This is hard to see in a repo where the assertions are passing, but see the snapshot update in that PR. (Note: the title is "improve expectTypeOf error messages" rather than referencing the update, since that's the net effect for end-users).

Here are what the examples of failing-test.d.ts in this repo look like:

Before:

image

After:

image

---

Related to https://github.com/vitest-dev/vitest/issues/1954 - @sheremet-va FYI. I don't think it closes it as that issue seems. to be more about how it fits into the vitest API/usage generally.

I also linked to my library in the readme.

~I've opened this as a draft as I'd like to publish v0.17.0 (rather than under the `next` dist-tag). I might actually bump to v1.0.0 too, I'm thinking of this as a release candidate (candidate).~

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it. (_There is one fix in https://github.com/mmkal/expect-type/pull/16 - `expectTypeOf<any>().toBeBoolean()` now produces an error, but I don't think that test needs to be duplicated here? I've checked this checkbox because I updated the error message snapshot tests._)
~- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example. (_err I needed to update it because I was updating a dependency? Should I delete this item?_)~

### Tests
- [x] Run the tests with `pnpm test:ci` (_also updated `test/typescript/test/runner.test.ts` and related snapshots to reflect the new error messages_)

<details>
<summary>Note: test/coverage-test failed with the below error but I think it's unrelated? _Edit: Yep, I got the same error on main_</summary>

image

Also node.spec.ts and math.ts seemed to have a newline added to them for some reason. Not sure what that's about.
</details>

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command. (_I haven't added docs, but I wrote lots in the pull request on expect-type. Is there a way to copy them here automatically and keep them in sync? Should I copy paste?)

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
> I also linked to my library in the readme.

You can also add a link in the docs!

> I don't think it closes it as that issue seems.

Yeah, it doesn't close the issue yet as there are other improvements that we need to make for typechecking.

Overall, PR looks good to me 👍🏻

**Comment by mmkal** [comment]
Oh I should update these docs too: https://vitest.dev/guide/testing-types.html#reading-errors

**Comment by mmkal** [comment]
@sheremet-va ok, added more docs re the error messages: https://github.com/vitest-dev/vitest/pull/4206/files#diff-58c52997981aa78c64ba261e445d5f5866f73205518e556a06beaa2d11fbcbff

I also updated typechecker.ts to put the type error on a single line so the useful information is as prominent as possible: https://github.com/vitest-dev/vitest/pull/4206/files#diff-02bca40f9c80e61170f4d69ec1aa9f68ff87c5ba3f0e49f7b5ab760362c9e69d

Here's the snapshot result: https://github.com/vitest-dev/vitest/pull/4206/files#diff-86e5c8d303f3cc24cb69cd88757cd83b4076c02f5d4c6b36d2f42792a1808d99

I don't know why the builds are red, but I don't think it's related to this pull request.

**Review by sheremet-va — APPROVED** [review]

**Comment by mmkal** [comment]
@sheremet-va loved the talk(!). I could do with some help with the pnpm lockfile when you get a minute. I ran `pnpm install` but CI doesn't seem to like what it generated.

**Comment by sheremet-va** [comment]
> I ran `pnpm install` but CI doesn't seem to like what it generated.

I think you have the older version installed. I run the command for you, should be fine now.

**Comment by sheremet-va** [comment]
Do you think we can have this in Vitest 1.0?

**Comment by mmkal** [comment]
Are you saying you'd rather hold off on this change until vitest v1.0.0? If so, let me know if there's a alternate branch I should be comparing to, or what I should do.

**Comment by sheremet-va** [comment]
> Are you saying you'd rather hold off on this change until vitest v1.0.0? If so, let me know if there's a alternate branch I should be comparing to, or what I should do. 

I asked when do you think this can be merged?

**Comment by mmkal** [comment]
Whenever it's green. I'll take another look today or tomorrow to see why it started failing. What's the timeline for v1?

**Comment by sheremet-va** [comment]
> I'll take another look today or tomorrow to see why it started failing.

Thank you.

> What's the timeline for v1?

This month.

It can always be merged later, I just wanted to know when you think this is ready since it's still in draft.

**Comment by sheremet-va** [comment]
> Ready for review at this point, would be great to get any help getting it over the line.

CI is in a poor state currently, so if your tests are working fine you shouldn't worry. From what I can see here, all the issues are also present on `main`.

**Comment by mmkal** [comment]
> > Ready for review at this point, would be great to get any help getting it over the line.
> 
> CI is in a poor state currently, so if your tests are working fine you shouldn't worry. From what I can see here, all the issues are also present on `main`.

@sheremet-va in that case, feel free to merge. If any issues emerge I will be able to help, but I'd like to get this in ASAP to avoid future merge conflicts.

**Pull request merged**
